Repository TeamSparker/Spark-iOS, pull requests merged in 2022-01, with the labels that each got.

#3 [Chore] #2 - 프로젝트 생성 및 깃허브 템플릿 추가
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Spark-iOS/Spark-iOS.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/Contents.json
  Spark-iOS/Spark-iOS/Resource/Constants/Const.swift
  Spark-iOS/Spark-iOS/Resource/Constants/Notification.swift
  Spark-iOS/Spark-iOS/Resource/Constants/Storyboard.swift
  Spark-iOS/Spark-iOS/Resource/Constants/ViewController.swift
  Spark-iOS/Spark-iOS/Resource/Constants/Xib.swift
  Spark-iOS/Spark-iOS/Resource/Fonts/TempFont.swift
  Spark-iOS/Spark-iOS/Resource/Info.plist
  Spark-iOS/Spark-iOS/Resource/Storyboards/Base.lproj/LaunchScreen.storyboard
  Spark-iOS/Spark-iOS/Resource/Storyboards/Base.lproj/Main.storyboard
  Spark-iOS/Spark-iOS/Source/AppDelegate.swift
  Spark-iOS/Spark-iOS/Source/AppModels/TempAppModel.swift
  Spark-iOS/Spark-iOS/Source/Cells/TempCell.swift
  Spark-iOS/Spark-iOS/Source/Extensions/UIColor+Extension.swift
  Spark-iOS/Spark-iOS/Source/Extensions/UIFont+Extension.swift
  Spark-iOS/Spark-iOS/Source/NetworkModels/TempModel.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/TempService.swift
  Spark-iOS/Spark-iOS/Source/Protocols/TempProtocol.swift
  Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/MainVC.swift
  Spark-iOS/Spark-iOS/Source/Views/TempView.swift
Labels: Chore, 👼타락pOwEr천사현규, P1 / Priority High

#8 [Docs] #5 - 리드미 수정
  README.md
Labels: 🦹t없e맑은水빈

#6 [Add] #4 - CocoaPods install
  Spark-iOS/Podfile
  Spark-iOS/Podfile.lock
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS.xcworkspace/contents.xcworkspacedata
Labels: Add, 🧚‍♀️Devil『쥬노』

#11 [Add] #7 - Color Asset 추가 및 Extension 작업
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Spark-iOS/Spark-iOS/Resource/Colors.xcassets/Contents.json
  Spark-iOS/Spark-iOS/Resource/Colors.xcassets/sparkBlack.colorset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Colors.xcassets/sparkBrightPinkred.colorset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Colors.xcassets/sparkDarkGray.colorset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Colors.xcassets/sparkDarkPinkRed.colorset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Colors.xcassets/sparkDeepGray.colorset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Colors.xcassets/sparkGray.colorset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Colors.xcassets/sparkLightGray.colorset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Colors.xcassets/sparkLightPinkred.colorset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Colors.xcassets/sparkMoreLightPinkred.colorset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Colors.xcassets/sparkMostLightPinkred.colorset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Colors.xcassets/sparkPinkRed.colorset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Colors.xcassets/sparkWhite.colorset/Contents.json
  Spark-iOS/Spark-iOS/Source/Extensions/UIColor+Extension.swift
Labels: Add, 🧚‍♀️Devil『쥬노』

#15 [Chore] #13 - 앱 이름 변경 및 프로젝트 설정
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
Labels: Chore, 👼타락pOwEr천사현규

#22 [Feat] #21 - 영문 폰트 파일 변경
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Fonts/Futura Bold font.ttf
  Spark-iOS/Spark-iOS/Resource/Fonts/Futura Bold.otf
  Spark-iOS/Spark-iOS/Resource/Fonts/Futura Medium Italic font.ttf
  Spark-iOS/Spark-iOS/Resource/Fonts/Futura Medium Italic.otf
  Spark-iOS/Spark-iOS/Resource/Fonts/Futura Medium.otf
  Spark-iOS/Spark-iOS/Resource/Fonts/futura medium bt.ttf
  Spark-iOS/Spark-iOS/Resource/Info.plist
Labels: Add, 🦹t없e맑은水빈

#25 [Feat] #16 - 피드뷰 레이아웃 구현
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Storyboards/TabBar/Feed.storyboard
  Spark-iOS/Spark-iOS/Source/Cells/FeedCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/FeedHeaderView.swift
  Spark-iOS/Spark-iOS/Source/Extensions/UIView+Extension.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
Labels: 🦹t없e맑은水빈, 🚨review_required🚨, P1 / Priority High

#27 [Feat] #23 - 스플래시, 로그인 뷰 구현
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Constants/Storyboard.swift
  Spark-iOS/Spark-iOS/Resource/Constants/UserDefaults.swift
  Spark-iOS/Spark-iOS/Resource/Constants/ViewController.swift
  Spark-iOS/Spark-iOS/Resource/Info.plist
  Spark-iOS/Spark-iOS/Resource/Storyboards/Base.lproj/LaunchScreen.storyboard
  Spark-iOS/Spark-iOS/Resource/Storyboards/Login/Login.storyboard
  Spark-iOS/Spark-iOS/Resource/Storyboards/Splash/Splash.storyboard
  Spark-iOS/Spark-iOS/Source/AppDelegate.swift
  Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Login/LoginVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Splash/SplashVC.swift
  Spark-iOS/Spark-iOS/Spark-iOS.entitlements
Labels: Feat, 👼타락pOwEr천사현규

#32 [Feat] #28 - 유저아이디, 엑세스토큰 UserDefaults 으로 저장 구현
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Constants/UserDefaultsKey.swift
  Spark-iOS/Spark-iOS/Source/AppDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Login/LoginVC.swift
Labels: Feat, 👼타락pOwEr천사현규

#33 [Feat] #30 - 언어 추가
  Spark-iOS/Spark-iOS/Resource/Info.plist
Labels: Feat, 👼타락pOwEr천사현규

#38 [Feat] #35 - 네비게이션 바 Extension 메서드로 구현
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Source/Extensions/UIColor+.swift
  Spark-iOS/Spark-iOS/Source/Extensions/UIFont+.swift
  Spark-iOS/Spark-iOS/Source/Extensions/UINavigationController+.swift
  Spark-iOS/Spark-iOS/Source/Extensions/UIView+.swift
  Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/MainTBC.swift
Labels: Feat, 👼타락pOwEr천사현규

#42 [Feat] #34 - 홈 습관방 조회뷰 구현
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/bgLinegridForWhite.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/bgLinegridForWhite.imageset/bgLinegridForWhite.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/bgLinegridForWhite.imageset/bgLinegridForWhite@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/bgLinegridForWhite.imageset/bgLinegridForWhite@3x.png
  Spark-iOS/Spark-iOS/Resource/Constants/Xib.swift
  Spark-iOS/Spark-iOS/Resource/Storyboards/TabBar/Base.lproj/Home.storyboard
  Spark-iOS/Spark-iOS/Source/Cells/Home/HomeHabitCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/Home/HomeHabitCVC.xib
  Spark-iOS/Spark-iOS/Source/Cells/Home/HomeWaitingCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/Home/HomeWaitingCVC.xib
  Spark-iOS/Spark-iOS/Source/Extensions/UINavigationController+.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/MainTBC.swift
Labels: Feat, 👼타락pOwEr천사현규

#39 [Feat] #26 - 대기방 구현
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/btnEdit.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/btnEdit.imageset/btnEdit.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/btnEdit.imageset/btnEdit@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/btnEdit.imageset/btnEdit@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/btnPrimary.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/btnPrimary.imageset/btnPrimary.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/btnPrimary.imageset/btnPrimary@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/btnPrimary.imageset/btnPrimary@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/btnRefresh.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/btnRefresh.imageset/btnRefresh.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/btnRefresh.imageset/btnRefresh@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/btnRefresh.imageset/btnRefresh@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/btnSmall.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/btnSmall.imageset/btnSmall.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/btnSmall.imageset/btnSmall@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/btnSmall.imageset/btnSmall@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icHome.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icHome.imageset/icHome.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icHome.imageset/icHome@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icHome.imageset/icHome@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icInformation.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icInformation.imageset/icInformation.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icInformation.imageset/icInformation@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icInformation.imageset/icInformation@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icMoreVerticalBlack.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icMoreVerticalBlack.imageset/icMoreVerticalBlack.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icMoreVerticalBlack.imageset/icMoreVerticalBlack@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icMoreVerticalBlack.imageset/icMoreVerticalBlack@3x.png
  Spark-iOS/Spark-iOS/Resource/Constants/Storyboard.swift
  Spark-iOS/Spark-iOS/Resource/Constants/ViewController.swift
  Spark-iOS/Spark-iOS/Resource/Info.plist
  Spark-iOS/Spark-iOS/Resource/Storyboards/Waiting/Waiting.storyboard
  Spark-iOS/Spark-iOS/Source/Cells/Feed/FeedCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/Feed/FeedHeaderView.swift
  Spark-iOS/Spark-iOS/Source/Cells/Waiting/WaitingFriendCVC.swift
  Spark-iOS/Spark-iOS/Source/Extensions/UILabel+.swift
  Spark-iOS/Spark-iOS/Source/Extensions/UIViewController+.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
  Spark-iOS/Spark-iOS/Spark-iOS.entitlements
Labels: Feat, 🦹t없e맑은水빈

#45 [Feat] #40 - 방생성 설정 뷰 구현
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Constants/Storyboard.swift
  Spark-iOS/Spark-iOS/Resource/Constants/ViewController.swift
  Spark-iOS/Spark-iOS/Resource/Storyboards/Create/CreateRoom.storyboard
  Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateRoomVC.swift
Labels: Feat, 🦹t없e맑은水빈

#52 [Feat] #43 - 코드로 참여하기 플로우 생성 및 보관함 애니메이션 구현
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkflakePattern.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkflakePattern.imageset/sparkflakePattern.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkflakePattern.imageset/sparkflakePattern@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkflakePattern.imageset/sparkflakePattern@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/ticketWelcome.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/ticketWelcome.imageset/ticketWelcome.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/ticketWelcome.imageset/ticketWelcome@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/ticketWelcome.imageset/ticketWelcome@3x.png
  Spark-iOS/Spark-iOS/Resource/Constants/Storyboard.swift
  Spark-iOS/Spark-iOS/Resource/Constants/ViewController.swift
  Spark-iOS/Spark-iOS/Resource/Constants/Xib.swift
  Spark-iOS/Spark-iOS/Resource/Storyboards/CodeJoin/CodeJoin.storyboard
  Spark-iOS/Spark-iOS/Resource/Storyboards/CodeJoin/JoinCheck.storyboard
  Spark-iOS/Spark-iOS/Resource/Storyboards/StorageMore/StorageMore.storyboard
  Spark-iOS/Spark-iOS/Source/Cells/Storage/DoingStorageCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/Storage/DoingStorageCVC.xib
  Spark-iOS/Spark-iOS/Source/Cells/Storage/DoneStorageCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/Storage/DoneStorageCVC.xib
  Spark-iOS/Spark-iOS/Source/Cells/Storage/FailStorageCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/Storage/FailStorageCVC.xib
  Spark-iOS/Spark-iOS/Source/Cells/StorageMore/MoreStorageCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/StorageMore/MoreStorageCVC.xib
  Spark-iOS/Spark-iOS/Source/Classes/LineAnimationView.swift
  Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/CodeJoin/CodeJoinVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/CodeJoin/JoinCheckVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/StorageMore/StorageMoreVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/StorageVC.swift
Labels: Feat, 🧚‍♀️Devil『쥬노』

#55 [Feat] #50 - 홈 플로팅버튼 구현
  Spark-iOS/Spark-iOS/Resource/Constants/Notification.swift
  Spark-iOS/Spark-iOS/Resource/Storyboards/TabBar/Base.lproj/Home.storyboard
  Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/MainTBC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/StorageVC.swift
Labels: Feat, 👼타락pOwEr천사현규, 🚨review_required🚨, P1 / Priority High

#56 [Feat] #53 - 나의 목표 작성 뷰 구현
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Constants/Storyboard.swift
  Spark-iOS/Spark-iOS/Resource/Constants/ViewController.swift
  Spark-iOS/Spark-iOS/Resource/Storyboards/GoalWriting/GoalWriting.storyboard
  Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/GoalWriting/GoalWritingVC.swift
Labels: Feat, 🦹t없e맑은水빈, 🚨review_required🚨, P1 / Priority High

#61 [Feat] #58 - 플로팅 버튼 터치 시 화면전환 및 코드 다시 입력하기 기능 구현
  Spark-iOS/Spark-iOS/Source/ViewControllers/CodeJoin/CodeJoinVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/CodeJoin/JoinCheckVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/StorageMore/StorageMoreVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/MainTBC.swift
Labels: Feat, 🧚‍♀️Devil『쥬노』, P1 / Priority High

#64 [Feat] #59 - 방생성 화면 플로우 연결
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icQuit.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icQuit.imageset/icQuit.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icQuit.imageset/icQuit@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icQuit.imageset/icQuit@3x.png
  Spark-iOS/Spark-iOS/Resource/Storyboards/Waiting/Waiting.storyboard
  Spark-iOS/Spark-iOS/Source/Extensions/UINavigationController+.swift
  Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateAuthVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/GoalWriting/GoalWritingVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/MainTBC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: Feat, 🦹t없e맑은水빈, 🚨review_required🚨

#69 [Feat] #57 - 사진인증 플로우 및 케이스별 업로드페이지 구현
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/stickerPhotoDefault.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/stickerPhotoDefault.imageset/stickerPhotoDefault.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/stickerPhotoDefault.imageset/stickerPhotoDefault@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/stickerPhotoDefault.imageset/stickerPhotoDefault@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/stickersBoth.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/stickersBoth.imageset/Group 564.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/stickersBoth.imageset/Group 564@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/stickersBoth.imageset/Group 564@3x.png
  Spark-iOS/Spark-iOS/Resource/Constants/Storyboard.swift
  Spark-iOS/Spark-iOS/Resource/Constants/ViewController.swift
  Spark-iOS/Spark-iOS/Resource/Info.plist
  Spark-iOS/Spark-iOS/Resource/Storyboards/Auth/AuthUpload.storyboard
  Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/CompleteAuth.storyboard
  Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/HabitAuth.storyboard
  Spark-iOS/Spark-iOS/Source/ViewControllers/CodeJoin/JoinCheckVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/GoalWriting/Auth/AuthUploadVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/CompleteAuthVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitAuthVC.swift
Labels: Feat, 🧚‍♀️Devil『쥬노』, P1 / Priority High

#67 [Feat] #60 - 스톱워치 뷰 구현
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/btnPlay.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/btnPlay.imageset/btnPlay.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/btnPlay.imageset/btnPlay@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/btnPlay.imageset/btnPlay@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/btnReset.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/btnReset.imageset/btnReset.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/btnReset.imageset/btnReset@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/btnReset.imageset/btnReset@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/btnStop.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/btnStop.imageset/btnStop.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/btnStop.imageset/btnStop@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/btnStop.imageset/btnStop@3x.png
  Spark-iOS/Spark-iOS/Resource/Constants/Notification.swift
  Spark-iOS/Spark-iOS/Resource/Constants/Storyboard.swift
  Spark-iOS/Spark-iOS/Resource/Constants/ViewController.swift
  Spark-iOS/Spark-iOS/Resource/Storyboards/Auth/AuthTimer/AuthTimer.storyboard
  Spark-iOS/Spark-iOS/Resource/Storyboards/Auth/AuthTimer/ResetPopup.storyboard
  Spark-iOS/Spark-iOS/Source/Classes/Stopwatch.swift
  Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/AuthTimerVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/ResetPopupVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
Labels: Feat, 🦹t없e맑은水빈, 🚨review_required🚨

#62 [Feat] #49 - Moya 초기세팅
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Constants/Const.swift
  Spark-iOS/Spark-iOS/Resource/Constants/Header.swift
  Spark-iOS/Spark-iOS/Resource/Constants/URL.swift
  Spark-iOS/Spark-iOS/Source/NetworkModels/GenericResponse.swift
  Spark-iOS/Spark-iOS/Source/NetworkModels/Home/HabitRoom.swift
  Spark-iOS/Spark-iOS/Source/NetworkModels/NetworkResult.swift
  Spark-iOS/Spark-iOS/Source/NetworkModels/TempModel.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Home/HomeAPI.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Home/HomeService.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Plugin/MoyaLoggerPlugin.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/TempService.swift
Labels: Feat, 👼타락pOwEr천사현규, P1 / Priority High

#73 [Feat] #66 - APNs 구현
  Spark-iOS/Podfile
  Spark-iOS/Podfile.lock
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/GoogleService-Info.plist
  Spark-iOS/Spark-iOS/Resource/Info.plist
  Spark-iOS/Spark-iOS/Source/AppDelegate.swift
  Spark-iOS/Spark-iOS/Spark-iOS.entitlements
Labels: Feat, 👼타락pOwEr천사현규, P1 / Priority High

#76 [Chore] #75 - 스톱워치 뷰 처음 시작 수정
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/AuthTimerVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/ResetPopupVC.swift
Labels: Chore, 🦹t없e맑은水빈

#74 [Add] #65 - SwiftLint 적용
  Spark-iOS/.swiftlint.yml
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Source/AppDelegate.swift
  Spark-iOS/Spark-iOS/Source/Cells/Home/HomeHabitCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/Waiting/WaitingFriendCVC.swift
  Spark-iOS/Spark-iOS/Source/Extensions/UIView+.swift
  Spark-iOS/Spark-iOS/Source/Extensions/UIViewController+.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Home/HomeService.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Plugin/MoyaLoggerPlugin.swift
  Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/CodeJoin/CodeJoinVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/CodeJoin/JoinCheckVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateAuthVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/GoalWriting/GoalWritingVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitAuthVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Login/LoginVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/StorageMore/StorageMoreVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/MainTBC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/StorageVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: Add, 👼타락pOwEr천사현규, P1 / Priority High

#77 [Feat] #70, #71 - 인증완료 팝업 구현 및 코드참여 팝업 애니메이션
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustHandClap.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustHandClap.imageset/illustHandClap.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustHandClap.imageset/illustHandClap@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustHandClap.imageset/illustHandClap@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/instaButton.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/instaButton.imageset/Group 412.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/instaButton.imageset/Group 412@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/instaButton.imageset/Group 412@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/instagram.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/instagram.imageset/instagram.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/instagram.imageset/instagram@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/instagram.imageset/instagram@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/stickerPhotoDefault.imageset/Contents 2.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/stickerPhotoDefault.imageset/stickerPhotoDefault 2.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/stickerPhotoDefault.imageset/stickerPhotoDefault@2x 2.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/stickerPhotoDefault.imageset/stickerPhotoDefault@3x 2.png
  Spark-iOS/Spark-iOS/Resource/Info.plist
  Spark-iOS/Spark-iOS/Resource/Storyboards/Auth/AuthUpload/AuthUpload.storyboard
  Spark-iOS/Spark-iOS/Resource/Storyboards/CodeJoin/CodeJoin.storyboard
  Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/CompleteAuth.storyboard
  Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/AuthTimerVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/CodeJoin/CodeJoinVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/CodeJoin/JoinCheckVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/CompleteAuthVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitAuthVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/StorageMore/StorageMoreVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/StorageVC.swift
Labels: Feat, 🧚‍♀️Devil『쥬노』, P2 / Priority Middle

#81 [Feat] #78 - 로티 인스톨 및 티켓 애니메이션 구현
  Spark-iOS/Podfile
  Spark-iOS/Podfile.lock
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustHandClap.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustHandClap.imageset/illustHandClap.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustHandClap.imageset/illustHandClap@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustHandClap.imageset/illustHandClap@3x.png
  Spark-iOS/Spark-iOS/Resource/Constants/Lottie.swift
  Spark-iOS/Spark-iOS/Resource/Lottie/ic_heart_active.json
  Spark-iOS/Spark-iOS/Resource/Lottie/illust_confetti.json
  Spark-iOS/Spark-iOS/Resource/Lottie/splash_iOS.json
  Spark-iOS/Spark-iOS/Resource/Lottie/ticket_welcome.json
  Spark-iOS/Spark-iOS/Resource/Storyboards/CodeJoin/JoinCheck.storyboard
  Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/CompleteAuth.storyboard
  Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/CodeJoin/JoinCheckVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/CompleteAuthVC.swift
Labels: Feat, 🧚‍♀️Devil『쥬노』, P2 / Priority Middle

#84 [Feat] #83 - 홈뷰 습관방 조회 서버 적용
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/ticketEmpty.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/ticketEmpty.imageset/ticketEmpty.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/ticketEmpty.imageset/ticketEmpty@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/ticketEmpty.imageset/ticketEmpty@3x.png
  Spark-iOS/Spark-iOS/Resource/Constants/Header.swift
  Spark-iOS/Spark-iOS/Resource/Constants/Xib.swift
  Spark-iOS/Spark-iOS/Source/AppDelegate.swift
  Spark-iOS/Spark-iOS/Source/Cells/Home/HomeEmptyCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/Home/HomeEmptyCVC.xib
  Spark-iOS/Spark-iOS/Source/NetworkModels/GenericResponse.swift
  Spark-iOS/Spark-iOS/Source/NetworkModels/Home/HabitRoom.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Home/HomeAPI.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Plugin/MoyaLoggerPlugin.swift
  Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
Labels: Feat, 👼타락pOwEr천사현규

#86 [Feat] #68 - 스톱워치 + 사진 인증하기 중 사진인증 뷰 구현
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/uploadEmptyView.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/uploadEmptyView.imageset/uploadEmptyView.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/uploadEmptyView.imageset/uploadEmptyView@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/uploadEmptyView.imageset/uploadEmptyView@3x.png
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/AuthTimerVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
Labels: Feat, 🦹t없e맑은水빈, 🚨review_required🚨

#87 [Feat] #80 - 대기방 서버 연결
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Source/Cells/Waiting/WaitingFriendCVC.swift
  Spark-iOS/Spark-iOS/Source/NetworkModels/Room/WaitingMember.swift
  Spark-iOS/Spark-iOS/Source/NetworkModels/Room/WaitingRoom.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomAPI.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomService.swift
  Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: Feat, 🦹t없e맑은水빈

#91 [Chore] #90 - Kingfisher pod install 및 extension 추가
  Spark-iOS/Podfile
  Spark-iOS/Podfile.lock
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Source/Cells/Home/HomeHabitCVC.xib
  Spark-iOS/Spark-iOS/Source/Extensions/UIImageView+.swift
Labels: Chore, 👼타락pOwEr천사현규

#95 [Feat] #89 - 피드뷰 피드 모아보기 서버 연결
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/tagEmpty.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/tagEmpty.imageset/tagEmpty.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/tagEmpty.imageset/tagEmpty@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/tagEmpty.imageset/tagEmpty@3x.png
  Spark-iOS/Spark-iOS/Source/Cells/Feed/FeedCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/Feed/FeedEmptyCVC.swift
  Spark-iOS/Spark-iOS/Source/NetworkModels/Feed/Feed.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Feed/FeedAPI.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Feed/FeedService.swift
  Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
Labels: Feat, 🦹t없e맑은水빈, 🚨review_required🚨

#92 [Feat] #88 - 코드로 참여하기 플로우 서버 연결
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Lottie/ticket_welcome.json
  Spark-iOS/Spark-iOS/Resource/Storyboards/CodeJoin/JoinCheck.storyboard
  Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/CompleteAuth.storyboard
  Spark-iOS/Spark-iOS/Source/NetworkModels/MyRoom/MyRoom.swift
  Spark-iOS/Spark-iOS/Source/NetworkModels/MyRoom/MyRoomCerti.swift
  Spark-iOS/Spark-iOS/Source/NetworkModels/Room/CodeJoinCheck.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/MyRoom/MyRoomAPI.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/MyRoom/MyRoomService.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomAPI.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomService.swift
  Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/CodeJoin/CodeJoinVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/CodeJoin/JoinCheckVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/CompleteAuthVC.swift
Labels: Feat, 🧚‍♀️Devil『쥬노』, P1 / Priority High

#99 [Feat] #96 - 피드뷰 좋아요, 좋아요 취소 서버 연결
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/grayBackground.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/grayBackground.imageset/grayBackground.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/grayBackground.imageset/grayBackground@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/grayBackground.imageset/grayBackground@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/uploadEmptyView.imageset/uploadEmptyView.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/uploadEmptyView.imageset/uploadEmptyView@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/uploadEmptyView.imageset/uploadEmptyView@3x.png
  Spark-iOS/Spark-iOS/Resource/Lottie/icHeartActive.json
  Spark-iOS/Spark-iOS/Source/Cells/Feed/FeedCVC.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Feed/FeedAPI.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Feed/FeedService.swift
  Spark-iOS/Spark-iOS/Source/Protocols/FeedCellDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
Labels: Feat, 🦹t없e맑은水빈, 🚨review_required🚨

#101 [Feat] #98 - Splash 로티 구현
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Constants/Lottie.swift
  Spark-iOS/Spark-iOS/Resource/Lottie/splash_bg_iOS.json
  Spark-iOS/Spark-iOS/Resource/Lottie/splash_iOS.json
  Spark-iOS/Spark-iOS/Resource/Lottie/splash_logo.json
  Spark-iOS/Spark-iOS/Resource/Storyboards/Base.lproj/LaunchScreen.storyboard
  Spark-iOS/Spark-iOS/Resource/Storyboards/Login/Login.storyboard
  Spark-iOS/Spark-iOS/Resource/Storyboards/Splash/Splash.storyboard
  Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/CodeJoin/JoinCheckVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Splash/SplashVC.swift
Labels: Feat, 👼타락pOwEr천사현규

#107 [Feat] #100 - 습관방 생성 서버 연결
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Source/Cells/Home/HomeHabitCVC.swift
  Spark-iOS/Spark-iOS/Source/NetworkModels/Room/CreateRoom.swift
  Spark-iOS/Spark-iOS/Source/NetworkModels/Room/RoomId.swift
  Spark-iOS/Spark-iOS/Source/NetworkModels/Room/WaitingRoom.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomAPI.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomService.swift
  Spark-iOS/Spark-iOS/Source/Protocols/TempProtocol.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateAuthVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: Feat, 🦹t없e맑은水빈, 🚨review_required🚨

#108 [Feat] #103 - 홈뷰 대기방 티켓 이미지 설정
  Spark-iOS/Spark-iOS/Source/Cells/Home/HomeHabitCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/Home/HomeWaitingCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/Home/HomeWaitingCVC.xib
  Spark-iOS/Spark-iOS/Source/ViewControllers/Splash/SplashVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
Labels: Feat, 👼타락pOwEr천사현규, 🚨review_required🚨

#105 [Feat] #97 - 스파크 보내기 뷰 구현 및 사진인증 서버 연결
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Constants/Storyboard.swift
  Spark-iOS/Spark-iOS/Resource/Constants/ViewController.swift
  Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/SendSpark.storyboard
  Spark-iOS/Spark-iOS/Source/Classes/CarouselLayout.swift
  Spark-iOS/Spark-iOS/Source/Classes/StatusButton.swift
  Spark-iOS/Spark-iOS/Source/NetworkModels/Room/AuthUpload.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomAPI.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomService.swift
  Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/CodeJoin/CodeJoinVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/SendSparkVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/StorageVC.swift
Labels: Feat, 🧚‍♀️Devil『쥬노』

#112 [Feat] #106 - 스파크 보내기 기능 서버 연결
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/SendSpark.storyboard
  Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomAPI.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomService.swift
  Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/SendSparkVC.swift
Labels: Feat, 🧚‍♀️Devil『쥬노』, P1 / Priority High

#114 [Feat] #109 - 습관방 시작 서버 연결
  Spark-iOS/Spark-iOS/Source/Extensions/UIViewController+.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomAPI.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomService.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: Feat, 🦹t없e맑은水빈, 🚨review_required🚨

#118 [Feat] #113 - 케이스별 dialogue 구현
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Constants/Storyboard.swift
  Spark-iOS/Spark-iOS/Resource/Constants/ViewController.swift
  Spark-iOS/Spark-iOS/Resource/Storyboards/Dialogue/Dialogue.storyboard
  Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Dialogue/DialogueVC.swift
Labels: Feat, 🧚‍♀️Devil『쥬노』, P2 / Priority Middle

#121 [Feat] #119 - 쉴래요 고민중 서버 연결
  Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/HabitAuth.storyboard
  Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomAPI.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomService.swift
  Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitAuthVC.swift
Labels: Feat, 🧚‍♀️Devil『쥬노』

#120 [Feat] #115 - 프로필 설정 뷰 레이아웃
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Constants/Storyboard.swift
  Spark-iOS/Spark-iOS/Resource/Constants/ViewController.swift
  Spark-iOS/Spark-iOS/Resource/Storyboards/CodeJoin/JoinCheck.storyboard
  Spark-iOS/Spark-iOS/Resource/Storyboards/Profile/ProfileSetting.storyboard
  Spark-iOS/Spark-iOS/Source/Extensions/UILabel+.swift
  Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/AuthTimerVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateAuthVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/GoalWriting/GoalWritingVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Profile/ProfileSettingVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: Feat, 🦹t없e맑은水빈

#124 [Feat] #72 - 뷰 디테일 수정
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Constants/Header.swift
  Spark-iOS/Spark-iOS/Resource/Info.plist
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/AuthTimerVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/ResetPopupVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateAuthVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/GoalWriting/GoalWritingVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Profile/ProfileSettingVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
  Spark-iOS/Spark-iOS/Source/Views/CreateAuth/PhotoAuthView.swift
  Spark-iOS/Spark-iOS/Source/Views/CreateAuth/TimerAuthView.swift
Labels: Fix, 🦹t없e맑은水빈, 🚨review_required🚨

#127 [Feat] #110 - 나의 목표 설정 서버 연결
  Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomAPI.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomService.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/GoalWriting/GoalWritingVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: Feat, 🦹t없e맑은水빈, 🚨review_required🚨

#128 [Feat] #126 - 로그인 서버 연결
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Constants/Header.swift
  Spark-iOS/Spark-iOS/Source/NetworkModels/Auth/Login.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Auth/AuthAPI.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Auth/AuthService.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Feed/FeedService.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Home/HomeService.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/MyRoom/MyRoomService.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomService.swift
  Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Login/LoginVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Profile/ProfileSettingVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Splash/SplashVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
Labels: Feat, 👼타락pOwEr천사현규

#132 [Feat] #129 - 대기방가는 플로우 처리
  Spark-iOS/Spark-iOS/Resource/Storyboards/CodeJoin/JoinCheck.storyboard
  Spark-iOS/Spark-iOS/Source/NetworkModels/Room/CodeJoinCheck.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomAPI.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomService.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/CodeJoin/CodeJoinVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/CodeJoin/JoinCheckVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/CompleteAuthVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Login/LoginVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: Feat, 👼타락pOwEr천사현규

#134 [Fix] #63 - 대기방 제외 기기대응
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Source/Cells/Feed/FeedCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/Waiting/WaitingFriendCVC.swift
  Spark-iOS/Spark-iOS/Source/Extensions/UIScreen+.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/AuthTimerVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateAuthVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/GoalWriting/GoalWritingVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
  Spark-iOS/Spark-iOS/Source/Views/CreateAuth/PhotoAuthView.swift
  Spark-iOS/Spark-iOS/Source/Views/CreateAuth/TimerAuthView.swift
Labels: Fix, 🦹t없e맑은水빈, 🚨review_required🚨

#136 [Chore] #135 - 빌드 숫자 업데이트(2) 및 시작 뷰컨 변경
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/CompleteAuthVC.swift
Labels: Chore, 👼타락pOwEr천사현규, 🚨review_required🚨

#141 [Feat] 13프로, 13미니, SE2 기기대응
  Spark-iOS/Spark-iOS/Resource/Storyboards/CodeJoin/CodeJoin.storyboard
  Spark-iOS/Spark-iOS/Resource/Storyboards/Create/CreateRoom.storyboard
  Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/CompleteAuth.storyboard
  Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/HabitAuth.storyboard
  Spark-iOS/Spark-iOS/Source/Cells/Storage/DoingStorageCVC.xib
  Spark-iOS/Spark-iOS/Source/Cells/StorageMore/MoreStorageCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/StorageMore/MoreStorageCVC.xib
  Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomService.swift
  Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/StorageVC.swift
Labels: Feat, 🧚‍♀️Devil『쥬노』, P2 / Priority Middle

#144 [Fix] #139 - 홈 엠티뷰 스크롤 막기
  Spark-iOS/Spark-iOS/Resource/Constants/Header.swift
  Spark-iOS/Spark-iOS/Source/Cells/Feed/FeedEmptyCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/Home/HomeEmptyCVC.xib
  Spark-iOS/Spark-iOS/Source/Cells/Home/HomeWaitingCVC.xib
  Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Splash/SplashVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
Labels: Fix, 🦹t없e맑은水빈, 🚨review_required🚨

#148 [Chore] #143 - API 헤더 변경 및 각종 뷰 디테일 변경
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/cardEmpty.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/cardEmpty.imageset/cardEmpty.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/cardEmpty.imageset/cardEmpty@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/cardEmpty.imageset/cardEmpty@3x.png
  Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/CompleteAuth.storyboard
  Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/HabitAuth.storyboard
  Spark-iOS/Spark-iOS/Resource/Storyboards/TabBar/Storage.storyboard
  Spark-iOS/Spark-iOS/Source/Classes/CarouselLayout.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Auth/AuthService.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/MyRoom/MyRoomService.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomService.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/CodeJoin/CodeJoinVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/CompleteAuthVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitAuthVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/StorageMore/StorageMoreVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/StorageVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: Fix, Chore, 🧚‍♀️Devil『쥬노』

#153 [Feat] #150 - 대기방 툴팁 기능 구현
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/photoToolTip.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/photoToolTip.imageset/photoToolTip.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/photoToolTip.imageset/photoToolTip@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/photoToolTip.imageset/photoToolTip@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/timerToolTip.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/timerToolTip.imageset/timerToolTip.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/timerToolTip.imageset/timerToolTip@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/timerToolTip.imageset/timerToolTip@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/tooltipPhoto.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/tooltipPhoto.imageset/tooltipPhoto.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/tooltipPhoto.imageset/tooltipPhoto@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/tooltipPhoto.imageset/tooltipPhoto@3x.png
  Spark-iOS/Spark-iOS/Source/Cells/Storage/DoingStorageCVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/StorageVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: Feat, 🧚‍♀️Devil『쥬노』

#156 [Fix] #145 - 습관 인증 플로우 연결
  Spark-iOS/Spark-iOS/Resource/Constants/Header.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomService.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/AuthTimerVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitAuthVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
Labels: Fix, 🦹t없e맑은水빈, 🚨review_required🚨

#158 [Feat] #155 - 습관방 만들기 화면전환 및 각종 코드 디테일 수정
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Source/AppDelegate.swift
  Spark-iOS/Spark-iOS/Source/Cells/Feed/FeedCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/HabitRoom/habitRoomMemberCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/Home/HomeWaitingCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/StorageMore/MoreStorageCVC.swift
  Spark-iOS/Spark-iOS/Source/Extensions/UIImage+.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Feed/FeedService.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitAuthVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Profile/ProfileSettingVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/StorageMore/StorageMoreVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: Feat, 🧚‍♀️Devil『쥬노』, P3 / Priority Low

#161 [Feat] #152 - 앱전반의 네비바 설정
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateAuthVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Login/LoginVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Profile/ProfileSettingVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Splash/SplashVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/StorageMore/StorageMoreVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/MainTBC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/StorageVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: Feat, 👼타락pOwEr천사현규

#162 [Feat] #157 - 습관 인증 후 피드로 화면 전환
  Spark-iOS/Spark-iOS/Resource/Storyboards/CodeJoin/JoinCheck.storyboard
  Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/CompleteAuth.storyboard
  Spark-iOS/Spark-iOS/Source/Cells/Feed/FeedCVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/CodeJoin/JoinCheckVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/CompleteAuthVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitAuthVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
Labels: Feat, 🦹t없e맑은水빈, 🚨review_required🚨

#163 [Fix] #159 - 피드뷰 레이아웃 수정
  Spark-iOS/Spark-iOS/Resource/Storyboards/TabBar/Feed.storyboard
  Spark-iOS/Spark-iOS/Source/Cells/Feed/FeedCVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/AuthTimerVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/CompleteAuthVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
Labels: Fix, 🦹t없e맑은水빈, 🚨review_required🚨

#167 [Chore] #166 - 이미지 리사이징 기기대응 및 쉴래요 고민중 버튼 분기처리
  Spark-iOS/Spark-iOS/Resource/Info.plist
  Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/HabitAuth.storyboard
  Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/HabitRoom.storyboard
  Spark-iOS/Spark-iOS/Source/Cells/StorageMore/MoreStorageCVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/CompleteAuthVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitAuthVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Profile/ProfileSettingVC.swift
Labels: Chore, 🧚‍♀️Devil『쥬노』

#168 [Fix] #165 - 습관방 멘트, 상태바, 상태 스티커 수정하기
  Spark-iOS/Spark-iOS/Resource/Constants/Notification.swift
  Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/HabitAuth.storyboard
  Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/HabitRoom.storyboard
  Spark-iOS/Spark-iOS/Source/Cells/HabitRoom/habitRoomMemberCVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitAuthVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
Labels: Feat, 👼타락pOwEr천사현규

#172 [Feat] #170 - 스파크 보내기 토스트메세지
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustHandSendSpark.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustHandSendSpark.imageset/illustHandSendspark.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustHandSendSpark.imageset/illustHandSendspark@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustHandSendSpark.imageset/illustHandSendspark@3x.png
  Spark-iOS/Spark-iOS/Source/Extensions/UIViewController+.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/SendSparkVC.swift
Labels: Feat, 🦹t없e맑은水빈, 🚨review_required🚨

#171 [Feat] #146 - 인스타그램 스토리 공유 기능 구현
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/CodeJoin/CodeJoinVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/CompleteAuthVC.swift
  Spark-iOS/Spark-iOS/Source/Views/CompleteAuth/ViewForRender.swift
Labels: Feat, 🧚‍♀️Devil『쥬노』

#173 [Feat] #169 - 습관방 플레이크 배경 수정, 대기방->홈 코드창 떠있음
  Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/HabitRoom.storyboard
  Spark-iOS/Spark-iOS/Source/Cells/Home/HomeHabitCVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: Feat, 👼타락pOwEr천사현규

#177 [Fix] #176 - 스플래쉬 문구 변경
  Spark-iOS/Spark-iOS/Source/ViewControllers/Splash/SplashVC.swift
Labels: Fix, 👼타락pOwEr천사현규

#180 [Fix] 홈 플로팅버튼 사라지는 문제해결
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: Fix, 👼타락pOwEr천사현규

#181 [Feat] #174 - 로딩뷰 구현
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Constants/Lottie.swift
  Spark-iOS/Spark-iOS/Resource/Lottie/loading3.json
  Spark-iOS/Spark-iOS/Source/Cells/Waiting/WaitingFriendCVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateAuthVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/StorageVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: Feat, 🦹t없e맑은水빈

#185 [Fix] #164 - 피드뷰 reloadData 문제
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: Feat, 👼타락pOwEr천사현규

#189 [Feat] #186 - 습관방 초기상태 세팅 및 홈 폰트 수정, 습관방 상세보기 로딩창 추가
  Spark-iOS/Spark-iOS/Source/Cells/Home/HomeHabitCVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
Labels: Feat, 👼타락pOwEr천사현규

#190 [Feat] #183 - 습관 인증하기 플로우 X버튼 추가 및 다이얼로그 연결
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/AuthTimerVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Dialogue/DialogueVC.swift
Labels: Feat, 🦹t없e맑은水빈, 🚨review_required🚨

#194 [Fix] #193 - 습관방 양쪽 흰배경수정, 레이아웃 수정
  Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/HabitRoom.storyboard
Labels: Fix, 👼타락pOwEr천사현규

#195 [Chore] #192 - 플로팅버튼 순서 수정
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/MainTBC.swift
Labels: Chore, 🦹t없e맑은水빈, 🚨review_required🚨

#198 [Feat] #197 - 피드뷰 하트 로컬 반영
  Spark-iOS/Spark-iOS/Source/Cells/Feed/FeedCVC.swift
  Spark-iOS/Spark-iOS/Source/NetworkModels/Feed/Feed.swift
  Spark-iOS/Spark-iOS/Source/Protocols/FeedCellDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
Labels: Feat, 👼타락pOwEr천사현규

#201 [Feat] #200 - 인스타 투터치 현상 해결
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/CompleteAuthVC.swift
Labels: Fix, 👼타락pOwEr천사현규

#202 [Fix] #196 - 대기방에서 홈으로 화면전환 수정
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: Fix, 🚨review_required🚨

#204 [Fix] #203 - 습관방 티켓 잘리던 에러
  Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/HabitRoom.storyboard
  Spark-iOS/Spark-iOS/Source/Cells/Storage/DoingStorageCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/Storage/DoneStorageCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/Storage/FailStorageCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/Storage/FailStorageCVC.xib
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
Labels: Fix, 👼타락pOwEr천사현규

#212 [Feat] #207 - 대기방 tooltip 레이아웃 수정 및 방생성 로딩창 추가
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: Feat, 🦹t없e맑은水빈, 🚨review_required🚨

#215 [Fix] #213 - SparkFlake 날짜 day62 분기처리 수정
  Spark-iOS/Spark-iOS/Source/Classes/SparkFlake.swift
Labels: Fix, 👼타락pOwEr천사현규, P1 / Priority High

#217 [Fix] #216 - 대기방에서 뷰 dismiss 분기처리
  Spark-iOS/Spark-iOS/Source/ViewControllers/CodeJoin/JoinCheckVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateAuthVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: Fix, 👼타락pOwEr천사현규, P1 / Priority High

#218 [Fix] #209 - 데이터를 계속 append하여 셀이 증식하는 문제 해결
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/StorageVC.swift
Labels: 🧚‍♀️Devil『쥬노』, P1 / Priority High

#220 [Feat] #214 - 대기방에서 스와이프 pop
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: Feat, 👼타락pOwEr천사현규, P1 / Priority High

#222 [Fix] #221 - 보관함 인증사진 모아보기 REST 이미지 우측 정렬되는 이슈
  Spark-iOS/Spark-iOS/Resource/Storyboards/StorageMore/StorageMore.storyboard
  Spark-iOS/Spark-iOS/Source/Cells/StorageMore/MoreStorageCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/StorageMore/MoreStorageCVC.xib
  Spark-iOS/Spark-iOS/Source/ViewControllers/StorageMore/StorageMoreVC.swift
Labels: Fix, 👼타락pOwEr천사현규, P1 / Priority High

#224 [Fix] #223 - 대기방에서 홈으로 이동시 플로팅 버튼 띄우기
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Constants/Cell.swift
  Spark-iOS/Spark-iOS/Source/Cells/Waiting/WaitingFriendCVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/StorageMore/StorageMoreVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/StorageVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: Fix, 👼타락pOwEr천사현규, P1 / Priority High
