Repository TeamSparker/Spark-iOS, pull requests merged in 2022-05, with the labels that each got.

#586 [Chore] #585 - 빌드 버전 변경(17)
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
Labels: Chore, 👼타락pOwEr천사현규

#588 [Fix] #587 - 스파크 보내기 트래킹 수정
  Spark-iOS/Spark-iOS/Source/AppDelegate.swift
  Spark-iOS/Spark-iOS/Source/Cells/HabitRoom/SendSparkCVC.swift
  Spark-iOS/Spark-iOS/Source/Protocols/SendSparkCellDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/SendSparkVC.swift
Labels: Fix, 👼타락pOwEr천사현규

#589 [Bug] #547 - 탭바 이동 후에 습관방 복제 및 강제종료 해결
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
Labels: 🐞bug, 👼타락pOwEr천사현규, 🙈 QA(Quality Assurance) 🙉

#592 [Fix] #591 - 알림뷰 contentImageView radius 수정
  Spark-iOS/Spark-iOS/Source/Cells/Notice/NoticeActiveCVC.swift
Labels: 🦹t없e맑은水빈

#594 [Fix] #593 - 알림 뷰 스크롤할 때 버튼 전환시 터지는 문제 해결
  Spark-iOS/Spark-iOS/Source/ViewControllers/Notice/NoticeVC.swift
Labels: Fix, 🦹t없e맑은水빈

#598 [Reject] #597 - 카메라, 앨범 권한 문구 수정 및 빌드 업데이트(21)
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
Labels: Chore, 👼타락pOwEr천사현규, 🫥 Reject

#602 [Chore] #601 - 앱 언어 변경
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
Labels: Chore, 👼타락pOwEr천사현규, 🐓 Release

#604 [Refactor] #571 - SendSparkButton 이니셜라이저를 활용한 초기화로 리펙토링
  Spark-iOS/Spark-iOS/Source/Classes/SendSparkButton.swift
Labels: 👷Refactor👷‍♂️, 👼타락pOwEr천사현규, 🐓 Release

#611 [Chore] #610 - 버전 및 빌드 업데이트(1.0.1)
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
Labels: Chore, 👼타락pOwEr천사현규, 🚨review_required🚨, 🐓 Release

#614 [Chore] #613 - release-1.0.1 -> main, develop 머지
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Source/Classes/SendSparkButton.swift
Labels: Chore, 👼타락pOwEr천사현규, 🐓 Release

#615 [Chore] #613 - release-1.0.1 -> develop 머지
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Source/Classes/SendSparkButton.swift
Labels: Chore, 👼타락pOwEr천사현규, 🐓 Release

#619 [Bug] #618 - 습관방 한 개일 때 삭제(실패, 방 삭제, 나가기) 후, 새로고침 후 사라지지 않는 버그
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
Labels: 🐞Bug, 👼타락pOwEr천사현규

#623 [Feat] #608 - 스플래시 뷰에서 OS 정보 서버로 보내기
  Spark-iOS/Spark-iOS/Source/NetworkServices/Auth/AuthService.swift
Labels: Feat, 👼타락pOwEr천사현규

#628 [Refeact] #622 - UserDefaults 사용 방법 리펙토링
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Constants/Header.swift
  Spark-iOS/Spark-iOS/Resource/Constants/Notification.swift
  Spark-iOS/Spark-iOS/Resource/Constants/UserDefaultsKey.swift
  Spark-iOS/Spark-iOS/Resource/Constants/UserDefaultsManager.swift
  Spark-iOS/Spark-iOS/Source/AppDelegate.swift
  Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/AuthTimerVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Login/LoginVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/MypageVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/WithdrawalVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Profile/ProfileSettingVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Splash/Onboarding/OnboardingVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Splash/SplashVC.swift
Labels: 👷Refactor👷‍♂️, 👼타락pOwEr천사현규
