Repository TeamSparker/Spark-iOS, pull requests merged in 2022-02, with the labels that each got.

#227 [Feat] #226 - 습관방에서 멤버 상태스티커 반영
  Spark-iOS/Spark-iOS/Source/Cells/HabitRoom/habitRoomMemberCVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
Labels: Feat, 👼타락pOwEr천사현규, P1 / Priority High

#219 [Feat] #210 - 피드 좋아요 로티 문제 해결
  Spark-iOS/Spark-iOS/Resource/Constants/Cell.swift
  Spark-iOS/Spark-iOS/Source/Cells/Feed/FeedCVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
Labels: 🦹t없e맑은水빈, 🖐help_wanted🖐, P1 / Priority High

#229 [Refactor] #228 - 스와이프해서 pop 코드 리펙토링
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/AuthTimerVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: Refactor, 👼타락pOwEr천사현규, 🚨review_required🚨

#232 [Feat] #225 - 인증사진 모아보기 뷰 타이머 인증 분기처리
  Spark-iOS/Spark-iOS/Source/Cells/StorageMore/MoreStorageCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/StorageMore/MoreStorageCVC.xib
  Spark-iOS/Spark-iOS/Source/ViewControllers/StorageMore/StorageMoreVC.swift
Labels: Feat, 🧚‍♀️Devil『쥬노』

#233 [Feat] #230 - 피드에 footer 추가
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Constants/Cell.swift
  Spark-iOS/Spark-iOS/Source/Cells/Feed/FeedEmptyCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/Feed/FeedFooterView.swift
  Spark-iOS/Spark-iOS/Source/Cells/Feed/FeedHeaderView.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
Labels: 🦹t없e맑은水빈, 🚨review_required🚨

#236 [Feat] #231 - 스파크 보내기 시 햅틱 구현
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Source/Classes/SendSparkButton.swift
  Spark-iOS/Spark-iOS/Source/Extensions/UIViewController+.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/SendSparkVC.swift
Labels: Feat, Refactor, 👼타락pOwEr천사현규

#235 [Chore] #234 - 빌드 버전 변경(6)
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
Labels: Chore, 👼타락pOwEr천사현규

#238 [Chore] #237 - 빌드 버전 변경(7)
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
Labels: Chore, 👼타락pOwEr천사현규

#240 [Fix] #239 - 습관방 로딩 시 셀 초기화 및 구분선 색깔 굵기 및 진하기 수정
  Spark-iOS/Spark-iOS/Source/Cells/HabitRoom/HabitRoomMemberCVC.xib
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
Labels: Fix, 👼타락pOwEr천사현규, 🙈 QA(Quality Assurance) 🙉

#243 [Fix] #241 - 나의 목표 작성 뷰 디테일 수정 및 extension 분리
  Spark-iOS/Spark-iOS/Source/Extensions/UIViewController+.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/GoalWriting/GoalWritingVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Profile/ProfileSettingVC.swift
Labels: Fix, 🦹t없e맑은水빈, 🙈 QA(Quality Assurance) 🙉

#247 [Fix] #244 - 대기방 뷰 디테일 수정
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: Fix, 🦹t없e맑은水빈, 🙈 QA(Quality Assurance) 🙉

#249 [Fix] #248 - 습관방 생성 뷰 텍스트필드 레이아웃 수정
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/GoalWriting/GoalWritingVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Profile/ProfileSettingVC.swift
Labels: Fix, 🦹t없e맑은水빈, 🙈 QA(Quality Assurance) 🙉

#251 [FIX] #242 - 습관방 티켓 폰트수정 및 인증하기 바텀시트 문구 수정
  Spark-iOS/.swiftlint.yml
  Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/HabitAuth.storyboard
  Spark-iOS/Spark-iOS/Source/Cells/Home/HomeHabitCVC.swift
Labels: Fix, 👼타락pOwEr천사현규, 🙈 QA(Quality Assurance) 🙉

#256 [Add] #252 - 플로팅버튼 라이브러리 재설치
  Spark-iOS/Podfile
  Spark-iOS/Podfile.lock
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/MainTBC.swift
Labels: Fix, 🦹t없e맑은水빈, 🙈 QA(Quality Assurance) 🙉

#261 [Refactor] #257 - 대기방 코드 리팩토링
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Source/Cells/HabitRoom/HabitRoomMemberCVC.swift
  Spark-iOS/Spark-iOS/Source/NetworkModels/Room/WaitingRoom.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: 👷Refactor👷‍♂️, 🦹t없e맑은水빈

#262 [Fix] #246 - 보관함 및 인증사진 모아보기 각종 QA
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/bgLinegridForBlackTransparent.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/bgLinegridForBlackTransparent.imageset/bgLinegridForBlackTransparent.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/bgLinegridForBlackTransparent.imageset/bgLinegridForBlackTransparent@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/bgLinegridForBlackTransparent.imageset/bgLinegridForBlackTransparent@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icFireDefaultGray.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icFireDefaultGray.imageset/icFireDefaultGray.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icFireDefaultGray.imageset/icFireDefaultGray@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icFireDefaultGray.imageset/icFireDefaultGray@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/stickerRestBigMybox.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/stickerRestBigMybox.imageset/stickerRestBigMybox.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/stickerRestBigMybox.imageset/stickerRestBigMybox@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/stickerRestBigMybox.imageset/stickerRestBigMybox@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/tagEmptyBox.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/tagEmptyBox.imageset/tagEmptyBox.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/tagEmptyBox.imageset/tagEmptyBox@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/tagEmptyBox.imageset/tagEmptyBox@3x.png
  Spark-iOS/Spark-iOS/Resource/Storyboards/StorageMore/StorageMore.storyboard
  Spark-iOS/Spark-iOS/Source/Cells/Storage/DoingStorageCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/Storage/DoingStorageCVC.xib
  Spark-iOS/Spark-iOS/Source/Cells/Storage/DoneStorageCVC.xib
  Spark-iOS/Spark-iOS/Source/Cells/Storage/FailStorageCVC.xib
  Spark-iOS/Spark-iOS/Source/Cells/StorageMore/MoreStorageCVC.xib
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/StorageVC.swift
Labels: Fix, 🧚‍♀️Devil『쥬노』, 🙈 QA(Quality Assurance) 🙉

#264 [Fix] #263 - 습관인증 스톱워치 뷰 버튼 레이아웃 변경
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/AuthTimerVC.swift
Labels: Fix, 🦹t없e맑은水빈, 🙈 QA(Quality Assurance) 🙉

#269 [Fix] #266 - 인스타 공유 팝업 UI 및 레이아웃 수정 #271 - 보관함 emptyView 분기처리 오류 수정 및 서버통신 시점 변경
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustHandClap.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustHandClap.imageset/illustHandClap.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustHandClap.imageset/illustHandClap@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustHandClap.imageset/illustHandClap@3x.png
  Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/CompleteAuth.storyboard
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/CompleteAuthVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/StorageVC.swift
Labels: Fix, 🧚‍♀️Devil『쥬노』, 🙈 QA(Quality Assurance) 🙉

#270 [Fix] #265 - 엠티뷰 레이아웃 수정
  Spark-iOS/Spark-iOS/Resource/Storyboards/TabBar/Storage.storyboard
  Spark-iOS/Spark-iOS/Source/Cells/Feed/FeedEmptyCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/Home/HomeEmptyCVC.xib
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/StorageVC.swift
Labels: Fix, 🦹t없e맑은水빈, 🙈 QA(Quality Assurance) 🙉

#268 [Fix] #267 - lastid 를 lastId 로 서버로 보낼 파라미터 네임 변경
  Spark-iOS/Spark-iOS/Source/NetworkServices/Feed/FeedService.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Home/HomeService.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/MyRoom/MyRoomService.swift
Labels: Fix, 👼타락pOwEr천사현규

#273 [Chore] #272 - 빌드 버전 변경(8)
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
Labels: Chore, 👼타락pOwEr천사현규

#276 [Fix] #274 - 인증사진 모아보기 타이머 표시 기능 연결
  Spark-iOS/Spark-iOS/Source/Cells/StorageMore/MoreStorageCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/StorageMore/MoreStorageCVC.xib
  Spark-iOS/Spark-iOS/Source/NetworkModels/MyRoom/MyRoomCerti.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/StorageMore/StorageMoreVC.swift
Labels: Fix, 🧚‍♀️Devil『쥬노』

#279 [Feat] #258 - 습관방 티켓 REST 이미지 에셋 추가 및 분기처리
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/tagRest.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/tagRest.imageset/tagRest.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/tagRest.imageset/tagRest@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/tagRest.imageset/tagRest@3x.png
  Spark-iOS/Spark-iOS/Source/Cells/Home/HomeHabitCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/Home/HomeHabitCVC.xib
  Spark-iOS/Spark-iOS/Source/NetworkModels/Home/HabitRoom.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
Labels: Feat, 👼타락pOwEr천사현규, 🙈 QA(Quality Assurance) 🙉

#282 [Fix] #281 - 나의 목표 작성 뷰 두번째 텍스트필드 활성화 안되는 문제 수정
  Spark-iOS/Spark-iOS/Source/ViewControllers/GoalWriting/GoalWritingVC.swift
Labels: Fix, 🦹t없e맑은水빈, 🙈 QA(Quality Assurance) 🙉

#283 [Chore] #280 - 빌드 버전 변경(9)
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
Labels: Chore, 👼타락pOwEr천사현규

#285 [Refactor] #275 - BottomButton 컴포넌트 분리
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Source/Classes/BottomButton.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/AuthTimerVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateAuthVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/GoalWriting/GoalWritingVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Profile/ProfileSettingVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: 👷Refactor👷‍♂️, 🦹t없e맑은水빈

#289 [Add] #286 - UIFont+ 타이포 추가
  Spark-iOS/Spark-iOS/Source/Extensions/UIFont+.swift
Labels: Add, 🦹t없e맑은水빈

#291 [Design] #290 - 대기방 토스트메세지 위치 수정, 하단 버튼 타이틀 수정
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: Design, 🦹t없e맑은水빈

#294 [Feat] #288 - 커스텀 네비게이션바 적용, #278 - 커스텀 네비게이션 바 만들기
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/HabitRoom.storyboard
  Spark-iOS/Spark-iOS/Resource/Storyboards/StorageMore/StorageMore.storyboard
  Spark-iOS/Spark-iOS/Resource/Storyboards/TabBar/Base.lproj/Home.storyboard
  Spark-iOS/Spark-iOS/Resource/Storyboards/TabBar/Storage.storyboard
  Spark-iOS/Spark-iOS/Source/Classes/LeftButtonNavigaitonBar.swift
  Spark-iOS/Spark-iOS/Source/Classes/LeftRightButtonsNavigationBar.swift
  Spark-iOS/Spark-iOS/Source/Classes/RightTwoButtonNavigationBar.swift
  Spark-iOS/Spark-iOS/Source/Classes/SparkNavigationBar.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/AuthTimerVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateAuthVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Dialogue/DialogueVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/StorageMore/StorageMoreVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/MainTBC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/StorageVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: Feat, 👼타락pOwEr천사현규, 🙈 QA(Quality Assurance) 🙉

#297 [Fix] #277 - 미완료 카드 플레이크 어셋 오류 수정
  Spark-iOS/Spark-iOS/Source/Cells/Storage/FailStorageCVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/StorageVC.swift
Labels: Fix, 🧚‍♀️Devil『쥬노』

#299 [Fix] #296 - SparkFlake 클래스 day66 열거형 분기처리 삭제
  Spark-iOS/Spark-iOS/Source/Classes/SparkFlake.swift
Labels: Fix, 👼타락pOwEr천사현규

#301 [Chore]#300 - Issue, Pull requests 양식 변경
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Chore, 👼타락pOwEr천사현규

#303 [Chore] #302 - Pull requests 스크린샷 첨부 양식 수정
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Chore, 👼타락pOwEr천사현규

#304 [Feat] #292 - 대기방에서 습관방 시작 팝업 구현 및 플로우 수정
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icBanuser.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icBanuser.imageset/icBanuser.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icBanuser.imageset/icBanuser@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icBanuser.imageset/icBanuser@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icPhone.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icPhone.imageset/icPhone.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icPhone.imageset/icPhone@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icPhone.imageset/icPhone@3x.png
  Spark-iOS/Spark-iOS/Resource/Constants/Storyboard.swift
  Spark-iOS/Spark-iOS/Resource/Constants/ViewController.swift
  Spark-iOS/Spark-iOS/Resource/Storyboards/Waiting/RoomStart.storyboard
  Spark-iOS/Spark-iOS/Source/Extensions/UIColor+.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/RoomStartVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: Feat, 🦹t없e맑은水빈

#309 [Feat] #284, #298 - 커스텀 액션시트 구현
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Source/Classes/SparkActionSheet.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Profile/ProfileSettingVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/StorageMore/StorageMoreVC.swift
Labels: Feat, 🧚‍♀️Devil『쥬노』

#313 [Feat] #305 - 대기방, 습관방 더보기(방 삭제, 방 나가기) 구현
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Constants/Storyboard.swift
  Spark-iOS/Spark-iOS/Resource/Constants/ViewController.swift
  Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/HabitRoomLeave.storyboard
  Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomAPI.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomService.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Dialogue/DialogueVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomLeaveVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: Feat, 🦹t없e맑은水빈
