Repository TeamSparker/Spark-iOS, pull requests merged in 2022-04, with the labels that each got.

#454 [Feat] #452 - 대기방에서 홈으로 갈 때 습관방 리스트 조회하기
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/AuthTimerVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: Feat, 👼타락pOwEr천사현규

#456 [Feat] #400 - SplashVC 에서 doorbell API 로 엑세스 토큰 갱신하기
  Spark-iOS/Spark-iOS/Source/ViewControllers/Splash/SplashVC.swift
Labels: Feat, 👼타락pOwEr천사현규, 🚨review_required🚨

#459 [Fix] #457 - 마이페이지, 알림뷰에서 스크롤시 헤더 고정시키지 않기
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/MypageVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/NotificationVC.swift
Labels: Fix, 👼타락pOwEr천사현규

#463 [Fix] #453 - 습관방 인증방식 선택 시 번갈아 활성화되는 문제 해결
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateAuthVC.swift
Labels: Fix, 🦹t없e맑은水빈

#464 [Feat] #455 - 스와이프 팝 제스처 extension 정리
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/AuthTimerVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Feed/FeedReportVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/MypageVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Notice/NoticeVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/StorageMore/StorageMoreVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: 👷Refactor👷‍♂️, 👼타락pOwEr천사현규

#469 [Feat] #468 - 회원 탈퇴 서버통신 연결
  Spark-iOS/Spark-iOS/Source/NetworkServices/Auth/AuthAPI.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Auth/AuthService.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/WithdrawalVC.swift
Labels: Feat, 👼타락pOwEr천사현규

#472 [Fix] #471 - 팝업창 subtitle 가운데 정렬하기
  Spark-iOS/Spark-iOS/Source/ViewControllers/Dialogue/CompleteFailDialogueVC.swift
Labels: Fix, 👼타락pOwEr천사현규, 🙈 QA(Quality Assurance) 🙉

#475 [Fix] #445 - 습관방 더보기 순서 변경
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
Labels: Fix, 🦹t없e맑은水빈

#477 [Fix] #476 - 습관 인증 스톱워치 백그라운드에서 멈추는 문제 해결
  Spark-iOS/Spark-iOS/Resource/Constants/UserDefaultsKey.swift
  Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/AuthTimerVC.swift
Labels: Fix, 🦹t없e맑은水빈, 🙈 QA(Quality Assurance) 🙉

#478 [Fix] #474 - 습관방 시간,목표 문구 변경
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
Labels: Fix, 👼타락pOwEr천사현규, 🙈 QA(Quality Assurance) 🙉

#482 [Design] #481 - 홈 엠티뷰 수정
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/bgHomeEmpty.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/bgHomeEmpty.imageset/bgHomeEmpty.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/bgHomeEmpty.imageset/bgHomeEmpty@1x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/bgHomeEmpty.imageset/bgHomeEmpty@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/bgHomeEmpty.imageset/bgHomeEmpty@3x.png
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
Labels: Design, 🦹t없e맑은水빈

#486 [Fix] #484 - 습관방 이용가이드 닫기 버튼 분기처리
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomGuideVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
Labels: Fix, 🦹t없e맑은水빈

#487 [Fix] #460, #461 - dDay 분기처리 및 보관함 카드 레이아웃 조정
  Spark-iOS/Spark-iOS/Source/Cells/StorageMore/MoreStorageCVC.swift
  Spark-iOS/Spark-iOS/Source/Classes/SparkFlake.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/StorageVC.swift
Labels: Fix, 🧚‍♀️Devil『쥬노』

#496 [Fix] #494 - 타이머 작동 중 화면 꺼짐 방지
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/AuthTimerVC.swift
Labels: Fix, 🦹t없e맑은水빈

#491 [Feat] #462 - 스파크 보내기 뷰 이모지 키보드 관련 레이아웃 대응
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/SendSparkVC.swift
Labels: Feat, Fix, 🧚‍♀️Devil『쥬노』

#503 [Fix] #499 - 나의 목표 수정 문구 변경
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
Labels: Fix, 🦹t없e맑은水빈

#501 [Fix] #493 - 알림뷰에서 리마인드 문구 변경 및 스위치 색상 변경
  Spark-iOS/Spark-iOS/Source/Cells/Mypage/NotificationTVC.swift
Labels: Fix, 👼타락pOwEr천사현규, 🙈 QA(Quality Assurance) 🙉

#502 [Fix] #498 - kingfisher 720*720 코드 수정
  Spark-iOS/Spark-iOS/Source/Extensions/UIImageView+.swift
Labels: Fix, 👼타락pOwEr천사현규

#504 [Fix] #497 - 플로팅버튼 폰트, 크기 수정
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/MainTBC.swift
Labels: Fix, 👼타락pOwEr천사현규

#505 [Refactor] #500 - UINavigationViewController+ 파일 삭제
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Source/Extensions/UINavigationController+.swift
Labels: 👷Refactor👷‍♂️, 👼타락pOwEr천사현규

#507 [Fix] #506 - 회원가입뷰에서 프로필 삭제 시 바텀 시트 닫기
  Spark-iOS/Spark-iOS/Source/ViewControllers/Profile/ProfileSettingVC.swift
Labels: Fix, 👼타락pOwEr천사현규

#510 [Chore] #509 - 빌드 버전 변경(14)
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
Labels: Chore, 👼타락pOwEr천사현규

#512 [Feat] #479 - 홈 알림 빨간불 서버통신 연결
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icNoticeNew.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icNoticeNew.imageset/icNoticeNew.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icNoticeNew.imageset/icNoticeNew@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icNoticeNew.imageset/icNoticeNew@3x.png
  Spark-iOS/Spark-iOS/Source/Classes/SparkNavigationBar/RightTwoButtonNavigationBar.swift
  Spark-iOS/Spark-iOS/Source/NetworkModels/Notice/NewNotice.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Notice/NoticeAPI.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Notice/NoticeService.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
Labels: Feat, 👼타락pOwEr천사현규

#514 [Feat] #467 - 이미지 리사이징해서 업로드하기
  Spark-iOS/Spark-iOS/Source/Extensions/UIImage+.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Auth/AuthService.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomService.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/User/UserService.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/EditProfileVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Profile/ProfileSettingVC.swift
Labels: Feat, 👼타락pOwEr천사현규

#515 [Fix] #508 - 플로팅버튼 독립적으로 터치되도록 수정
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/MainTBC.swift
Labels: Fix, 👼타락pOwEr천사현규

#518 [Feat] #470 - 대표이미지 변경 뷰 셀 필터링 및 완료버튼 동작 수정
  Spark-iOS/Spark-iOS/Source/ViewControllers/StorageMore/StorageMoreVC.swift
Labels: Feat, Fix, 🧚‍♀️Devil『쥬노』

#517 [Fix] #516 - 습관인증 pop해서 돌아왔을때 타이머 노티 재설정
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/AuthTimerVC.swift
Labels: Fix, 🦹t없e맑은水빈, 🙈 QA(Quality Assurance) 🙉

#519 [Add] #401 - 습관방 이용가이드 일러스트 추가
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustTip1.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustTip1.imageset/illustTip1.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustTip1.imageset/illustTip1@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustTip1.imageset/illustTip1@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustTip2.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustTip2.imageset/illustTip2.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustTip2.imageset/illustTip2@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustTip2.imageset/illustTip2@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustTip3.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustTip3.imageset/illustTip3.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustTip3.imageset/illustTip3@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustTip3.imageset/illustTip3@3x.png
  Spark-iOS/Spark-iOS/Source/Cells/HabitRoom/HabitRoomGuideCVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomGuideVC.swift
Labels: Add, 🦹t없e맑은水빈

#524 [Fix] #523 - 회원 탈퇴 체크 박스 선택시 텍스트 컬러 변경
  Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/WithdrawalVC.swift
Labels: Fix, 👼타락pOwEr천사현규, 🙈 QA(Quality Assurance) 🙉

#520 [Fix] #513 - 이모지 키보드 오류 수정
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/SendSparkVC.swift
Labels: Feat, Fix, 🧚‍♀️Devil『쥬노』

#522 [Fix] #521 - 인증완료 팝업 문구 수정
  Spark-iOS/Spark-iOS/Source/Classes/SparkFlake.swift
Labels: Fix, 🧚‍♀️Devil『쥬노』

#527 [Feat] #526 - 유니버셜 링크 구현
  Spark-iOS/Spark-iOS/Resource/Info.plist
  Spark-iOS/Spark-iOS/Spark-iOS.entitlements
Labels: Feat, 👼타락pOwEr천사현규

#529 [Fix] #528 - 프로필 수정 뷰 노티 삭제
  Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/EditProfileVC.swift
Labels: Fix, 🦹t없e맑은水빈, 🙈 QA(Quality Assurance) 🙉

#531 [Chore] #530 - 빌드 버전 변경(15)
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
Labels: Chore, 👼타락pOwEr천사현규

#533 [Feat] #511 - 현재 앱 버전 확인 후 최신 업데이트 안내
  Spark-iOS/Spark-iOS/Resource/Constants/URL.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Splash/SplashVC.swift
Labels: Feat, 👼타락pOwEr천사현규

#535 [Fix] #534 - 방 생성 뷰 노티 추가, 삭제하는 시점 수정
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateRoomVC.swift
Labels: Fix, 🦹t없e맑은水빈

#537 [Fix] #536 - 홈 로딩 끝나고 알림 빨간불 반영
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
Labels: Fix, 👼타락pOwEr천사현규

#538 [Feat] #480 - 프로필 설정 및 생성뷰 이모지 키보드 레이아웃 대응
  Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/EditProfileVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Profile/ProfileSettingVC.swift
Labels: Feat, 👼타락pOwEr천사현규

#542 [Chore] #541 - 빌드 버전 변경(16)
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
Labels: Chore, 👼타락pOwEr천사현규

#540 [Feat] #525 - RxSwift, Rxocoa pod install 및 throttle로 알림뷰 버튼 중복 탭 막음
  Spark-iOS/Podfile
  Spark-iOS/Podfile.lock
  Spark-iOS/Spark-iOS/Source/ViewControllers/Notice/NoticeVC.swift
Labels: Fix, 🦹t없e맑은水빈

#545 [Fix] #544 - 홈에서 리프레쉬할 때 엠티뷰가 등장하는 버그
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
Labels: Fix, 👼타락pOwEr천사현규, 🙈 QA(Quality Assurance) 🙉

#551 [Bug] #550 - 습관방 생성 확인 뷰에서 swipe back gesture 막기
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateSuccessVC.swift
Labels: 🐞bug

#552 [Fix] #549 - 대기방 개설자 방 삭제 시 토스트메세지 분기처리
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: Fix, 🦹t없e맑은水빈

#554 [Fix] #553 - 강제 업데이트 다이얼로그 구현
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS.xcworkspace/contents.xcworkspacedata
  Spark-iOS/Spark-iOS/Resource/Constants/Storyboard.swift
  Spark-iOS/Spark-iOS/Resource/Constants/ViewController.swift
  Spark-iOS/Spark-iOS/Resource/Storyboards/Dialogue/Dialogue.storyboard
  Spark-iOS/Spark-iOS/Resource/Storyboards/Dialogue/SingleResponseDialogue.storyboard
  Spark-iOS/Spark-iOS/Source/ViewControllers/Dialogue/DialogueVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Dialogue/SingleResponseDialogueVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Splash/SplashVC.swift
Labels: Fix, 👼타락pOwEr천사현규

#555 [Feat] #546 - 스파크 보내기 버튼 throttle 적용
  Spark-iOS/Podfile.lock
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustHandClap.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustHandClap.imageset/illustHandClap.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustHandClap.imageset/illustHandClap@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustHandClap.imageset/illustHandClap@3x.png
  Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/CompleteAuth.storyboard
  Spark-iOS/Spark-iOS/Source/Cells/HabitRoom/SendSparkCVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/SendSparkVC.swift
Labels: Feat, 🧚‍♀️Devil『쥬노』

#557 [Fix] #556 - 노션 주소가 변경되어 URL 수정
  Spark-iOS/Spark-iOS/Resource/Constants/URL.swift
Labels: Fix, 👼타락pOwEr천사현규

#558 [Fix] #539 - 마이페이지에서 기본프로필의 경우 가끔 보이지 않는 버그
  Spark-iOS/Spark-iOS.xcworkspace/contents.xcworkspacedata
  Spark-iOS/Spark-iOS/Source/Cells/Mypage/MypageProfileTVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/EditProfileVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/MypageVC.swift
Labels: Fix, 👼타락pOwEr천사현규, 🙈 QA(Quality Assurance) 🙉

#565 [Fix] #562 - 나의 목표 작성 뷰 이모지 키보드 대응
  Spark-iOS/Podfile.lock
  Spark-iOS/Spark-iOS/Source/ViewControllers/GoalWriting/GoalWritingVC.swift
Labels: Fix, 🦹t없e맑은水빈

#564 [Feat] #563 - Tracking 상수 파일 추가 및 피드, 습관방 입장하기, 습관 인증하기 이벤트 로깅 코드 추가
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Constants/Tracking.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/AuthTimerVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: Feat, 🦹t없e맑은水빈

#568 [Feat] #567 - 홈, 습관방에 haptic 추가
  Spark-iOS/Spark-iOS/Source/ViewControllers/Dialogue/CompleteFailDialogueVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Dialogue/LifeDiminishDialogueVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/SendSparkVC.swift
Labels: Feat, 👼타락pOwEr천사현규

#570 [Feat] #569 - 트래킹 코드 추가
  Spark-iOS/Spark-iOS/Resource/Constants/Tracking.swift
  Spark-iOS/Spark-iOS/Source/Cells/HabitRoom/SendSparkCVC.swift
  Spark-iOS/Spark-iOS/Source/Classes/SendSparkButton.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitAuthVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Login/LoginVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Profile/ProfileSettingVC.swift
Labels: Feat, 👼타락pOwEr천사현규

#573 [Feat] #572 - 보관함, 코드로 참여, 인스타 공유, 인증 완료 트래킹 코드 추가
  Spark-iOS/Podfile.lock
  Spark-iOS/Spark-iOS/Resource/Constants/Tracking.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/CodeJoin/CodeJoinVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/CompleteAuthVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/StorageVC.swift
Labels: Feat, 🧚‍♀️Devil『쥬노』

#574 [Fix] #566 - 트래킹 수정
  Spark-iOS/Podfile.lock
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/AuthTimerVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateAuthVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: Fix, 🦹t없e맑은水빈

#576 [Feat] #575 - 대표이미지 변경 뷰 서버 연결
  Spark-iOS/Spark-iOS/Source/NetworkModels/MyRoom/MyRoomCerti.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/MyRoom/MyRoomAPI.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/MyRoom/MyRoomService.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/StorageMore/StorageMoreVC.swift
Labels: Feat, 🧚‍♀️Devil『쥬노』

#578 [Fix] #577 - 트래킹 이벤트 item name 변경
  Spark-iOS/Spark-iOS/Source/Cells/HabitRoom/SendSparkCVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/CodeJoin/CodeJoinVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateAuthVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/CompleteAuthVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitAuthVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Profile/ProfileSettingVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/StorageVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: Fix, 👼타락pOwEr천사현규

#580 [Chore] #579 - 앱 언어 Korea 변경
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
Labels: Chore, 👼타락pOwEr천사현규

#581 [Feat] #559 - 프로필 수정 완료 후 로딩뷰 추가
  Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/EditProfileVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Profile/ProfileSettingVC.swift
Labels: Chore, 👼타락pOwEr천사현규

#583 [Bug] #548 - 방 생성 뷰에서 스와이프 pop 제스처하면 화면 멈춤 해결
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/AuthTimerVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Feed/FeedReportVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/MypageVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Notice/NoticeVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/StorageMore/StorageMoreVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: 🐞bug, 👼타락pOwEr천사현규, 🙈 QA(Quality Assurance) 🙉

#584 [Feat] #582 - 푸시알림으로 앱을 열 경우 트래킹
  Spark-iOS/Spark-iOS/Resource/Constants/Tracking.swift
  Spark-iOS/Spark-iOS/Source/AppDelegate.swift
Labels: 🐞bug, 👼타락pOwEr천사현규, 🙈 QA(Quality Assurance) 🙉
