Repository TeamSparker/Spark-iOS, pull requests merged in 2022-03, with the labels that each got.

#316 [Feat] #314 - 쉴래요 다이얼로그 추가
  Spark-iOS/Spark-iOS/Resource/Storyboards/Dialogue/Dialogue.storyboard
  Spark-iOS/Spark-iOS/Source/ViewControllers/Dialogue/DialogueVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitAuthVC.swift
Labels: Feat, 👼타락pOwEr천사현규

#318 [Feat] #310 - 방 생성 완료 뷰 구현
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Constants/Storyboard.swift
  Spark-iOS/Spark-iOS/Resource/Constants/ViewController.swift
  Spark-iOS/Spark-iOS/Resource/Storyboards/CodeJoin/JoinCheck.storyboard
  Spark-iOS/Spark-iOS/Resource/Storyboards/Create/CreateSuccess.storyboard
  Spark-iOS/Spark-iOS/Source/Classes/BottomButton.swift
  Spark-iOS/Spark-iOS/Source/Extensions/UIViewController+.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/AuthTimerVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/CodeJoin/JoinCheckVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateAuthVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateSuccessVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Dialogue/DialogueVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/GoalWriting/GoalWritingVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Profile/ProfileSettingVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: Feat, 🦹t없e맑은水빈

#320 [Feat] #312 - 인증사진 모아보기 대표이미지 변경 뷰 구현
  Spark-iOS/Spark-iOS/Source/Cells/StorageMore/MoreStorageCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/StorageMore/MoreStorageCVC.xib
  Spark-iOS/Spark-iOS/Source/Classes/LeftButtonNavigaitonBar.swift
  Spark-iOS/Spark-iOS/Source/Classes/LeftRightButtonsNavigationBar.swift
  Spark-iOS/Spark-iOS/Source/Classes/SparkActionSheet.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/StorageMore/StorageMoreVC.swift
Labels: Feat, 🧚‍♀️Devil『쥬노』

#322 [Feat] #205 - 습관방 더보기 구현
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
Labels: Feat, 👼타락pOwEr천사현규

#325 [Refactor] #324 - 습관방 리프레시 메서드 네이밍 변경
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
Labels: 👷Refactor👷‍♂️, 👼타락pOwEr천사현규

#321 [Feat] #317 - customActionSheet coverVertical 애니메이션 구현
  Spark-iOS/Spark-iOS/Source/Cells/StorageMore/MoreStorageCVC.swift
  Spark-iOS/Spark-iOS/Source/Classes/SparkActionSheet.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Profile/ProfileSettingVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/StorageMore/StorageMoreVC.swift
Labels: Feat, 🧚‍♀️Devil『쥬노』

#331 [Chore] #329 - 대기방 멘트 수정 반영
  Spark-iOS/Spark-iOS/Source/ViewControllers/Dialogue/DialogueVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/RoomStartVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: Chore, 🦹t없e맑은水빈

#335 [Refactor] #334 - 리사이징된 이미지 반영
  Spark-iOS/Spark-iOS/Source/Cells/Feed/FeedCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/Waiting/WaitingFriendCVC.swift
  Spark-iOS/Spark-iOS/Source/NetworkModels/Feed/Feed.swift
  Spark-iOS/Spark-iOS/Source/NetworkModels/Room/WaitingRoom.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: 👷Refactor👷‍♂️, 🦹t없e맑은水빈

#341 [Feat] #332 - 마이페이지 구현
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icArrow.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icArrow.imageset/icArrow.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icArrow.imageset/icArrow@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icArrow.imageset/icArrow@3x.png
  Spark-iOS/Spark-iOS/Resource/Constants/Cell.swift
  Spark-iOS/Spark-iOS/Resource/Constants/Storyboard.swift
  Spark-iOS/Spark-iOS/Resource/Constants/ViewController.swift
  Spark-iOS/Spark-iOS/Resource/Storyboards/Mypage/Mypage.storyboard
  Spark-iOS/Spark-iOS/Source/Cells/Mypage/MypageDefaultTVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/Mypage/MypageProfileTVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/Mypage/MypageTableHeaderView.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/MypageVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
Labels: Feat, 👼타락pOwEr천사현규

#340 [Chore] #339 - 다이얼로그 멘트 수정 반영
  Spark-iOS/Spark-iOS/Source/ViewControllers/Dialogue/DialogueVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomLeaveVC.swift
Labels: Chore, 🦹t없e맑은水빈

#344 [Feat] #315 - 스파크 보내기 뷰 수정 및 텍스트필드로 메시지 전송 구현
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Constants/Cell.swift
  Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/SendSpark.storyboard
  Spark-iOS/Spark-iOS/Source/Cells/HabitRoom/HabitRoomMemberCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/HabitRoom/SendSparkCVC.swift
  Spark-iOS/Spark-iOS/Source/Classes/SendSparkButton.swift
  Spark-iOS/Spark-iOS/Source/Extensions/UIImage+.swift
  Spark-iOS/Spark-iOS/Source/Extensions/UIScreen+.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/ResetPopupVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/SendSparkVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/MainTBC.swift
Labels: Feat, 🧚‍♀️Devil『쥬노』

#346 [Feat] #333 - 리사이징된 이미지 받아오도록 수정
  Spark-iOS/Spark-iOS/Source/Cells/Storage/DoingStorageCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/Storage/DoneStorageCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/Storage/FailStorageCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/StorageMore/MoreStorageCVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/CompleteAuthVC.swift
  Spark-iOS/Spark-iOS/Source/Views/CompleteAuth/ViewForRender.swift
Labels: Fix, 🧚‍♀️Devil『쥬노』

#354 [Feat] #327, #328 - 인증사진 모아보기 대표이미지 변경 API 연결 및 보관함 viewWillAppear에서 통신으로 수정
  Spark-iOS/Spark-iOS/Source/Cells/StorageMore/MoreStorageCVC.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/MyRoom/MyRoomAPI.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/MyRoom/MyRoomService.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/StorageMore/StorageMoreVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/StorageVC.swift
Labels: Feat, 🧚‍♀️Devil『쥬노』

#355 [Feat] #353 - 피드 신고 서버 연결
  Spark-iOS/Spark-iOS/Resource/Constants/Notification.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Feed/FeedAPI.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Feed/FeedService.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Feed/FeedReportVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
Labels: Feat, 🦹t없e맑은水빈

#356 [Feat] #350 - 로그아웃 구현
  Spark-iOS/Spark-iOS/Source/ViewControllers/Dialogue/DialogueVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/MypageVC.swift
Labels: Feat, 👼타락pOwEr천사현규

#361 [Fix] #360 - 로그아웃 다이얼로그 삭제
  Spark-iOS/Spark-iOS/Source/ViewControllers/Dialogue/DialogueVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/MypageVC.swift
Labels: Fix, 👼타락pOwEr천사현규

#363 [Feat] #348 - 알림뷰 구현
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/noticeEmpty.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/noticeEmpty.imageset/noticeEmpty.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/noticeEmpty.imageset/noticeEmpty@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/noticeEmpty.imageset/noticeEmpty@3x.png
  Spark-iOS/Spark-iOS/Resource/Constants/Cell.swift
  Spark-iOS/Spark-iOS/Resource/Constants/Storyboard.swift
  Spark-iOS/Spark-iOS/Resource/Constants/ViewController.swift
  Spark-iOS/Spark-iOS/Resource/Storyboards/Notice/Notice.storyboard
  Spark-iOS/Spark-iOS/Source/Cells/Notice/NoticeActiveCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/Notice/NoticeServiceCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/Notice/NoticeUpdateHeaderView.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Notice/NoticeVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
Labels: Feat, 🦹t없e맑은水빈

#365 [Fix] #358 - 피드 중복신고 분기처리 삭제
  Spark-iOS/Spark-iOS/Source/ViewControllers/Feed/FeedReportVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
Labels: Fix, 🦹t없e맑은水빈

#366 [Feat] #352 - 마이페이지 고객센터-문의하기 구현
  Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/MypageVC.swift
Labels: Feat, 👼타락pOwEr천사현규

#369 [Design] #368 - 방생성 완료 뷰 로티 추가
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateSuccessVC.swift
Labels: Design, 🦹t없e맑은水빈

#370 [Feat] #367 - 분기별 인증완료 팝업 구현
  Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/CompleteAuth.storyboard
  Spark-iOS/Spark-iOS/Source/Classes/SparkFlake.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/CompleteAuthVC.swift
Labels: Feat, 🧚‍♀️Devil『쥬노』

#373 [Feat] #364 - 알림뷰 서버 연결
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Source/Cells/Notice/NoticeActiveCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/Notice/NoticeServiceCVC.swift
  Spark-iOS/Spark-iOS/Source/NetworkModels/Notice/ActiveNotice.swift
  Spark-iOS/Spark-iOS/Source/NetworkModels/Notice/ServiceNotice.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Notice/NoticeAPI.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Notice/NoticeService.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Notice/NoticeVC.swift
Labels: Feat, 🦹t없e맑은水빈

#374 [Feat] #362 - 피드 내 인증인 경우 더보기 버튼 hidden 처리
  Spark-iOS/Spark-iOS/Source/Cells/Feed/FeedCVC.swift
  Spark-iOS/Spark-iOS/Source/NetworkModels/Feed/Feed.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
Labels: Feat, 🦹t없e맑은水빈

#378 [Feat] #375 - 홈 성공/실패 방 분기처리 및 다이얼로그 추가
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/property1TicketRight4Dark.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/property1TicketRight4Dark.imageset/property1TicketRight4Dark.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/property1TicketRight4Dark.imageset/property1TicketRight4Dark@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/property1TicketRight4Dark.imageset/property1TicketRight4Dark@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/property1TicketRight4FoldDark.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/property1TicketRight4FoldDark.imageset/property1TicketRight4FoldDark.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/property1TicketRight4FoldDark.imageset/property1TicketRight4FoldDark@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/property1TicketRight4FoldDark.imageset/property1TicketRight4FoldDark@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkflakePattern2.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkflakePattern2.imageset/sparkflakePattern2.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkflakePattern2.imageset/sparkflakePattern2@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkflakePattern2.imageset/sparkflakePattern2@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/tagOhno.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/tagOhno.imageset/tagOhno.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/tagOhno.imageset/tagOhno@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/tagOhno.imageset/tagOhno@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/tagSuccess.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/tagSuccess.imageset/tagSuccess.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/tagSuccess.imageset/tagSuccess@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/tagSuccess.imageset/tagSuccess@3x.png
  Spark-iOS/Spark-iOS/Resource/Constants/Storyboard.swift
  Spark-iOS/Spark-iOS/Resource/Constants/ViewController.swift
  Spark-iOS/Spark-iOS/Resource/Storyboards/Dialogue/CompleteFailDialogue.storyboard
  Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/CompleteAuth.storyboard
  Spark-iOS/Spark-iOS/Source/Cells/Home/HomeHabitCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/Home/HomeHabitCVC.xib
  Spark-iOS/Spark-iOS/Source/NetworkModels/Home/HabitRoom.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Dialogue/CompleteFailDialogueVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
Labels: Feat, 👼타락pOwEr천사현규

#377 [Feat] #371 - 보관함 엠티뷰와 실패카드 day1 분기처리 및 프로토콜 소스파일 분리
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Storyboards/TabBar/Storage.storyboard
  Spark-iOS/Spark-iOS/Source/Cells/HabitRoom/SendSparkCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/Storage/FailStorageCVC.swift
  Spark-iOS/Spark-iOS/Source/Classes/CarouselLayout.swift
  Spark-iOS/Spark-iOS/Source/Protocols/SendSparkCellDelegate.swift
  Spark-iOS/Spark-iOS/Source/Protocols/SendThumbnailURLDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/StorageMore/StorageMoreVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/StorageVC.swift
Labels: Feat, 🧚‍♀️Devil『쥬노』

#380 [Feat] #379 - 홈 성공/실패 티켓 읽음 처리 서버연결
  Spark-iOS/Spark-iOS/Resource/Constants/Notification.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomAPI.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomService.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Dialogue/CompleteFailDialogueVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
Labels: Feat, 👼타락pOwEr천사현규

#381 [Feat] #372 - 온보딩 뷰 구현
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/bgOnboarding.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/bgOnboarding.imageset/bgOnboarding.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/bgOnboarding.imageset/bgOnboarding@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/bgOnboarding.imageset/bgOnboarding@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustOnboarding1.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustOnboarding1.imageset/illustOnboarding1.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustOnboarding1.imageset/illustOnboarding1@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustOnboarding1.imageset/illustOnboarding1@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustOnboarding2.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustOnboarding2.imageset/illustOnboarding2.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustOnboarding2.imageset/illustOnboarding2@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustOnboarding2.imageset/illustOnboarding2@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustOnboarding3.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustOnboarding3.imageset/illustOnboarding3.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustOnboarding3.imageset/illustOnboarding3@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustOnboarding3.imageset/illustOnboarding3@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustOnboarding4.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustOnboarding4.imageset/illustOnboarding4.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustOnboarding4.imageset/illustOnboarding4@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustOnboarding4.imageset/illustOnboarding4@3x.png
  Spark-iOS/Spark-iOS/Resource/Constants/Cell.swift
  Spark-iOS/Spark-iOS/Resource/Constants/Storyboard.swift
  Spark-iOS/Spark-iOS/Resource/Constants/ViewController.swift
  Spark-iOS/Spark-iOS/Resource/Storyboards/Onboarding/Onboarding.storyboard
  Spark-iOS/Spark-iOS/Source/Cells/HabitRoom/SendSparkCVC 2.swift
  Spark-iOS/Spark-iOS/Source/Cells/Onboarding/OnboardingCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/Onboarding/OnboardingCVCViewModel.swift
  Spark-iOS/Spark-iOS/Source/Protocols/ProfileImageDelegate 2.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Splash/Onboarding/OnboardingVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Splash/SplashVC.swift
Labels: Feat, 🧚‍♀️Devil『쥬노』

#385 [Fix] #382 - 홈, 피드 엠티뷰 수정
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/bgHomeEmpty.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/bgHomeEmpty.imageset/bgHomeEmpty.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/bgHomeEmpty.imageset/bgHomeEmpty@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/bgHomeEmpty.imageset/bgHomeEmpty@3x.png
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
Labels: Fix, 🦹t없e맑은水빈

#395 [Feat] #394 - Kingfisher placeholder 에 따른 분기처리
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkDarkGrayPlaceholder.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkDarkGrayPlaceholder.imageset/sparkDarkGrayPlaceholder.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkDarkGrayPlaceholder.imageset/sparkDarkGrayPlaceholder@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkDarkGrayPlaceholder.imageset/sparkDarkGrayPlaceholder@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkLightGrayPlaceholder.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkLightGrayPlaceholder.imageset/placeholder.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkLightGrayPlaceholder.imageset/placeholder@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkLightGrayPlaceholder.imageset/placeholder@3x.png
  Spark-iOS/Spark-iOS/Source/Cells/StorageMore/MoreStorageCVC.swift
  Spark-iOS/Spark-iOS/Source/Extensions/UIImageView+.swift
Labels: Feat, 👼타락pOwEr천사현규

#397 [Feat] #396 - 스파크사용가이드, 약관 및 정책 노션 인앱 연결
  Spark-iOS/Spark-iOS/Resource/Constants/URL.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/MypageVC.swift
Labels: Feat, 👼타락pOwEr천사현규

#399 [Feat] #388 - 습관방 이용가이드 구현
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Constants/Cell.swift
  Spark-iOS/Spark-iOS/Resource/Constants/Storyboard.swift
  Spark-iOS/Spark-iOS/Resource/Constants/UserDefaultsKey.swift
  Spark-iOS/Spark-iOS/Resource/Constants/ViewController.swift
  Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/HabitRoomGuide.storyboard
  Spark-iOS/Spark-iOS/Source/Cells/HabitRoom/HabitRoomGuideCVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomGuideVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
Labels: Feat, 🦹t없e맑은水빈

#403 [Feat] #398 - APNs notification service extension 사용해서 커스텀하기
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/SparkNotificationService/Info.plist
  Spark-iOS/SparkNotificationService/NotificationService.swift
Labels: Feat, 👼타락pOwEr천사현규

#387 [Feat] #351 - 커스텀 탭바 구현
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Source/Classes/SparkNavigationBar/LeftButtonNavigaitonBar.swift
  Spark-iOS/Spark-iOS/Source/Classes/SparkNavigationBar/LeftRightButtonsNavigationBar.swift
  Spark-iOS/Spark-iOS/Source/Classes/SparkNavigationBar/RightTwoButtonNavigationBar.swift
  Spark-iOS/Spark-iOS/Source/Classes/SparkNavigationBar/SparkActionSheet.swift
  Spark-iOS/Spark-iOS/Source/Classes/SparkNavigationBar/SparkNavigationBar.swift
  Spark-iOS/Spark-iOS/Source/Classes/SparkTabBar/SparkTabBar.swift
  Spark-iOS/Spark-iOS/Source/Classes/SparkTabBar/SparkTabBarController.swift
  Spark-iOS/Spark-iOS/Source/Classes/SparkTabBar/SparkTabBarItem.swift
  Spark-iOS/Spark-iOS/Source/Protocols/SparkTabBar/SparkTabBarDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/MainTBC.swift
Labels: Feat, 👼타락pOwEr천사현규, P1 / Priority High

#407 [Feat] #386 - 푸시할때 탭바 숨기기 및 플로팅 버튼 등장 시기 조절
  Spark-iOS/Spark-iOS/Source/Cells/Feed/FeedCVC.swift
  Spark-iOS/Spark-iOS/Source/Protocols/FeedCellDelegate.swift
  Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/CodeJoin/CodeJoinVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/CodeJoin/JoinCheckVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Feed/FeedReportVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/CompleteAuthVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitAuthVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/MypageVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Notice/NoticeVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/StorageMore/StorageMoreVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/StorageVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: Feat, 👼타락pOwEr천사현규, P1 / Priority High

#405 [Feat] #402 - 피드 게시물 하나인 경우 footer 로딩 막기
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
Labels: Fix, 🦹t없e맑은水빈

#406 [Feat] #404 - 홈, 피드 최초 습관방, 게시물 생성 시 안보이는 문제 해결
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
Labels: Fix, 🦹t없e맑은水빈

#409 [Chore] #408 - 빌드 버전 변경(11)
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
Labels: Chore, 👼타락pOwEr천사현규

#411 [Design] #410 - 홈 하단 inset 조절 및 커스텀 탭바에 맞추기
  Spark-iOS/Spark-iOS/Resource/Storyboards/TabBar/Base.lproj/Home.storyboard
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
Labels: Design, 👼타락pOwEr천사현규

#415 [Fix] #412 - 피드 레이아웃 및 isFirstScroll 조건 수정
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
Labels: Fix, 🦹t없e맑은水빈

#416 [Fix] #376 - 알림뷰 문제 해결
  Spark-iOS/Spark-iOS/Source/Extensions/UIFont+.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Notice/NoticeVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
Labels: Fix, 🦹t없e맑은水빈

#419 [Feat] #418 - 마이페이지 오픈소스 라이브러리 노션 인앱 연결
  Spark-iOS/Spark-iOS/Resource/Constants/URL.swift
  Spark-iOS/Spark-iOS/Source/Cells/Mypage/MypageDefaultTVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/MypageVC.swift
Labels: Feat, 👼타락pOwEr천사현규

#421 [Fix] #420 - 홈 티켓 흰줄 제거 및 프로필 모서리 수정
  Spark-iOS/Spark-iOS/Source/Cells/Home/HomeHabitCVC.swift
Labels: Fix, 👼타락pOwEr천사현규

#423 [Design] #422 - 습관방 이용가이드 스크롤 영역 height 조정
  Spark-iOS/Spark-iOS/Source/Cells/HabitRoom/HabitRoomGuideCVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomGuideVC.swift
Labels: Design, 🦹t없e맑은水빈

#427 [Feat] #425 - 습관 시작 후 습관방 이동 플로우 적용
  Spark-iOS/Spark-iOS/Resource/Constants/Notification.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: Feat, 🦹t없e맑은水빈

#428 [Design] #417 - 홈 성공/실패 팝업 로티 추가
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Constants/Lottie.swift
  Spark-iOS/Spark-iOS/Resource/Lottie/homeCardFail.json
  Spark-iOS/Spark-iOS/Resource/Lottie/homeCardSuccess.json
  Spark-iOS/Spark-iOS/Source/ViewControllers/Dialogue/CompleteFailDialogueVC.swift
Labels: Design, 👼타락pOwEr천사현규

#432 [Feat] #383 - 마이페이지 회원탈퇴 뷰 구현
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/btnCheckBox.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/btnCheckBox.imageset/btnCheckBox.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/btnCheckBox.imageset/btnCheckBox@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/btnCheckBox.imageset/btnCheckBox@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/btnCheckBoxDefault.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/btnCheckBoxDefault.imageset/btnCheckBoxDefault.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/btnCheckBoxDefault.imageset/btnCheckBoxDefault@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/btnCheckBoxDefault.imageset/btnCheckBoxDefault@3x.png
  Spark-iOS/Spark-iOS/Resource/Constants/Storyboard.swift
  Spark-iOS/Spark-iOS/Resource/Constants/ViewController.swift
  Spark-iOS/Spark-iOS/Resource/Storyboards/Mypage/Withdrawal.storyboard
  Spark-iOS/Spark-iOS/Source/Cells/Mypage/MypageDefaultTVC.swift
  Spark-iOS/Spark-iOS/Source/Classes/SparkNavigationBar/LeftButtonNavigaitonBar.swift
  Spark-iOS/Spark-iOS/Source/Protocols/WithdrawalCellDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/AuthTimerVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateAuthVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Dialogue/DialogueVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Feed/FeedReportVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/SendSparkVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/EditProfileVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/MypageVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/WithdrawalVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Notice/NoticeVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/StorageMore/StorageMoreVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: Feat, 👼타락pOwEr천사현규

#434 [Feat] #389 - 생명 감소 알림 뷰 구현
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustLifeDecrease.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustLifeDecrease.imageset/illustLifeDecrease.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustLifeDecrease.imageset/illustLifeDecrease@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/illustLifeDecrease.imageset/illustLifeDecrease@3x.png
  Spark-iOS/Spark-iOS/Resource/Constants/Storyboard.swift
  Spark-iOS/Spark-iOS/Resource/Constants/ViewController.swift
  Spark-iOS/Spark-iOS/Resource/Storyboards/Dialogue/LifeDiminishDialogue.storyboard
  Spark-iOS/Spark-iOS/Source/NetworkModels/Room/HabitRoomDetail.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Dialogue/LifeDiminishDialogueVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomGuideVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
Labels: Feat, 🧚‍♀️Devil『쥬노』

#435 [Fix] #424 - 만료된 토큰의 경우 메시지가 뜨지 않도록 처리
  Spark-iOS/Spark-iOS/Source/ViewControllers/CodeJoin/CodeJoinVC.swift
Labels: Fix, 🧚‍♀️Devil『쥬노』

#439 [Fix] #433 - 약관 및 정책, 오픈소스 라이브러리 노션 URL 변경
  Spark-iOS/Spark-iOS/Resource/Constants/URL.swift
Labels: Feat, 👼타락pOwEr천사현규

#438 [Feat] #437 - 마이페이지 알림뷰 서버연결
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Source/Cells/HabitRoom/SendSparkCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/Mypage/NotificationTVC.swift
  Spark-iOS/Spark-iOS/Source/NetworkModels/Notice/NoticeSetting.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Notice/NoticeAPI.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Notice/NoticeService.swift
  Spark-iOS/Spark-iOS/Source/Protocols/NotificationCellDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/NotificationVC.swift
Labels: Feat, 👼타락pOwEr천사현규

#440 [Feat] #430 - 마이페이지 로그아웃, 애플/카카오 회원탈퇴 및 서버연결
  Spark-iOS/Spark-iOS/Source/NetworkServices/Auth/AuthAPI.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Auth/AuthService.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/MypageVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/WithdrawalVC.swift
Labels: Feat, 👼타락pOwEr천사현규

#441 [Feat] #431 - 로그인 이용약관, 개인정보 처리 방침 노션 연결
  Spark-iOS/Spark-iOS/Resource/Constants/URL.swift
  Spark-iOS/Spark-iOS/Source/Cells/Feed/FeedHeaderView.swift
  Spark-iOS/Spark-iOS/Source/Cells/Home/HomeHabitCVC.swift
  Spark-iOS/Spark-iOS/Source/Cells/Mypage/NotificationTVC.swift
  Spark-iOS/Spark-iOS/Source/Extensions/UILabel+.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/CompleteAuthVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Login/LoginVC.swift
Labels: Feat, 👼타락pOwEr천사현규

#443 [Chore] #442 - 빌드버전 변경 및 최소 지원 버전 변경
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
Labels: Chore, 👼타락pOwEr천사현규

#449 [Fix] #444 - 재로그인시 이전 계정으로 로그인되는 버그
  Spark-iOS/Spark-iOS/Resource/Constants/Const.swift
  Spark-iOS/Spark-iOS/Resource/Constants/Header.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Auth/AuthService.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Feed/FeedService.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Home/HomeService.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/MyRoom/MyRoomService.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Notice/NoticeService.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomService.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/User/UserService.swift
Labels: Fix, 👼타락pOwEr천사현규

#451 [Chore] #429 - 나의 목표 작성, 프로필 설정, 방 생성 뷰에서 화면전환 시 노티 삭제
  Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/GoalWriting/GoalWritingVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Profile/ProfileSettingVC.swift
Labels: Chore, 🦹t없e맑은水빈
