Repository TeamSparker/Spark-iOS, pull requests merged in 2022-11, with the labels that each got.

#674 [Chore] #673 - 이미지 에셋 변경 및 fastlane fastfile 수정
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkFlakeSparkflake1.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkFlakeSparkflake1.imageset/sparkFlakeSparkflake1.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkFlakeSparkflake1.imageset/sparkFlakeSparkflake1@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkFlakeSparkflake1.imageset/sparkFlakeSparkflake1@3x.png
  Spark-iOS/fastlane/Fastfile
Labels: Chore, 👼타락pOwEr천사현규

#683 [Design] #682 - 불꽃 결정 로드맵 이름 변경
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
Labels: Design, 👼타락pOwEr천사현규

#685 [Chore] #684 - app extension 의 버전 업데이트 및 fastlaen 수정
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/fastlane/Fastfile
Labels: Chore, 👼타락pOwEr천사현규

#687 [Chore] #686 - fastlane release lane 의 build scheme 수정
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/fastlane/Fastfile
Labels: Chore, 👼타락pOwEr천사현규, 🚨review_required🚨, P1 / Priority High

#688 [Chore] #687 - 1.2.0 릴리즈를 위한 main 브랜치로 머지
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/fastlane/Fastfile
Labels: Chore, Hotfix

#691 [Bug] #690 - activeList, serviceList 초기화 시점 변경
  Spark-iOS/Spark-iOS/Source/ViewControllers/Notice/NoticeVC.swift
Labels: 🐞Bug, 🦹t없e맑은水빈
