Repository TeamSparker/Spark-iOS, pull requests merged in 2022-10, with the labels that each got.

#651 [Chore] #644 - 서버 호스트 주소 및 키 값 삭제
  .gitignore
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS.xcodeproj/xcshareddata/xcschemes/Spark-beta.xcscheme
  Spark-iOS/Spark-iOS.xcodeproj/xcshareddata/xcschemes/Spark-debug.xcscheme
  Spark-iOS/Spark-iOS.xcodeproj/xcshareddata/xcschemes/Spark-release.xcscheme
  Spark-iOS/Spark-iOS/Resource/Constants/URL.swift
  Spark-iOS/Spark-iOS/Resource/Info.plist
  Spark-iOS/Spark-iOS/Source/AppDelegate.swift
Labels: 👷Refactor👷‍♂️, Chore, 👼타락pOwEr천사현규

#657 [Feat] #655 - HabitRoomDetail 모델 수정 및 습관방 생명 빨콩, 화면 전환 추가
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icBadgeNew.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icBadgeNew.imageset/icBadgeNew.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icBadgeNew.imageset/icBadgeNew@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/icBadgeNew.imageset/icBadgeNew@3x.png
  Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/HabitRoom.storyboard
  Spark-iOS/Spark-iOS/Source/NetworkModels/Room/HabitRoomDetail.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
Labels: Fix, 🦹t없e맑은水빈

#661 [Feat] #660 - 생명 타임라인 API 연결
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Source/Cells/LifeTimeLine/LifeTimeLineCVC.swift
  Spark-iOS/Spark-iOS/Source/NetworkModels/Room/TimeLine.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomAPI.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomService.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/LifeTimeLine/LifeTimeLineVC.swift
Labels: Feat, 🦹t없e맑은水빈

#665 [Chore] #664 - release-1.0.4 브랜치로 develop 브랜치 merge
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Source/Cells/LifeTimeLine/LifeTimeLineCVC.swift
  Spark-iOS/Spark-iOS/Source/NetworkModels/Room/TimeLine.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomAPI.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomService.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/LifeTimeLine/LifeTimeLineVC.swift
Labels: Chore, 👼타락pOwEr천사현규

#659 [Chore] #654- 앱 자동 배포를 위한 Fastlane 설정
  .gitignore
  Spark-iOS/Gemfile
  Spark-iOS/Gemfile.lock
  Spark-iOS/Podfile.lock
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Info.plist
  Spark-iOS/fastlane/Appfile
  Spark-iOS/fastlane/Deliverfile
  Spark-iOS/fastlane/Fastfile
  Spark-iOS/fastlane/README.md
Labels: Chore, 👼타락pOwEr천사현규

#667 [Chore] #664 - release-1.0.4 브랜치로 develop 브랜치 merge
  .gitignore
  Spark-iOS/Gemfile
  Spark-iOS/Gemfile.lock
  Spark-iOS/Podfile.lock
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Info.plist
  Spark-iOS/fastlane/Appfile
  Spark-iOS/fastlane/Deliverfile
  Spark-iOS/fastlane/Fastfile
  Spark-iOS/fastlane/README.md
Labels: Chore, 👼타락pOwEr천사현규

#669 [Feat] #666 - 생명 타임라인 트래킹 추가
  Spark-iOS/Podfile.lock
  Spark-iOS/Spark-iOS/Resource/Constants/Tracking.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
Labels: Feat, 🦹t없e맑은水빈

#663 [Feat] #662 - 불꽃 결정 로드맵 팝업 뷰 구현
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/property1DashSparkFlake1.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/property1DashSparkFlake1.imageset/property1DashSparkFlake1.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/property1DashSparkFlake1.imageset/property1DashSparkFlake1@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/property1DashSparkFlake1.imageset/property1DashSparkFlake1@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/property1DashSparkFlake2.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/property1DashSparkFlake2.imageset/property1DashSparkFlake2.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/property1DashSparkFlake2.imageset/property1DashSparkFlake2@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/property1DashSparkFlake2.imageset/property1DashSparkFlake2@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/property1DashSparkFlake3.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/property1DashSparkFlake3.imageset/property1DashSparkFlake3.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/property1DashSparkFlake3.imageset/property1DashSparkFlake3@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/property1DashSparkFlake3.imageset/property1DashSparkFlake3@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/property1DashSparkFlake4.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/property1DashSparkFlake4.imageset/property1DashSparkFlake4.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/property1DashSparkFlake4.imageset/property1DashSparkFlake4@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/property1DashSparkFlake4.imageset/property1DashSparkFlake4@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/property1DashSparkFlake5.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/property1DashSparkFlake5.imageset/property1DashSparkFlake5.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/property1DashSparkFlake5.imageset/property1DashSparkFlake5@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/property1DashSparkFlake5.imageset/property1DashSparkFlake5@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/property1DashSparkFlake6.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/property1DashSparkFlake6.imageset/property1DashSparkFlake6.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/property1DashSparkFlake6.imageset/property1DashSparkFlake6@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/property1DashSparkFlake6.imageset/property1DashSparkFlake6@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkFlakeSparkFlake1.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkFlakeSparkFlake1.imageset/sparkFlakeSparkFlake1.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkFlakeSparkFlake1.imageset/sparkFlakeSparkFlake1@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkFlakeSparkFlake1.imageset/sparkFlakeSparkFlake1@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkFlakeSparkflake2.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkFlakeSparkflake2.imageset/sparkFlakeSparkflake2.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkFlakeSparkflake2.imageset/sparkFlakeSparkflake2@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkFlakeSparkflake2.imageset/sparkFlakeSparkflake2@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkFlakeSparkflake3.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkFlakeSparkflake3.imageset/sparkFlakeSparkflake3.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkFlakeSparkflake3.imageset/sparkFlakeSparkflake3@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkFlakeSparkflake3.imageset/sparkFlakeSparkflake3@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkFlakeSparkflake4.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkFlakeSparkflake4.imageset/sparkFlakeSparkflake4.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkFlakeSparkflake4.imageset/sparkFlakeSparkflake4@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkFlakeSparkflake4.imageset/sparkFlakeSparkflake4@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkFlakeSparkflake5.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkFlakeSparkflake5.imageset/sparkFlakeSparkflake5.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkFlakeSparkflake5.imageset/sparkFlakeSparkflake5@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkFlakeSparkflake5.imageset/sparkFlakeSparkflake5@3x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkFlakeSparkflake6.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkFlakeSparkflake6.imageset/sparkFlakeSparkflake6.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkFlakeSparkflake6.imageset/sparkFlakeSparkflake6@2x.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkFlakeSparkflake6.imageset/sparkFlakeSparkflake6@3x.png
  Spark-iOS/Spark-iOS/Resource/Constants/Cell.swift
  Spark-iOS/Spark-iOS/Resource/Constants/Storyboard.swift
  Spark-iOS/Spark-iOS/Resource/Constants/ViewController.swift
  Spark-iOS/Spark-iOS/Resource/Storyboards/Dialogue/UpgradeFlakeDialogue.storyboard
  Spark-iOS/Spark-iOS/Source/AppModels/UpgradeFlake/UpgradeFlake.swift
  Spark-iOS/Spark-iOS/Source/Cells/HabitRoom/UpgradeFlakeCVC.swift
  Spark-iOS/Spark-iOS/Source/Classes/SparkFlake.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Dialogue/UpgradeFlakeDialogueVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
Labels: Feat, 👼타락pOwEr천사현규

#670 [Feat] #668 - 불꽃 결정 로드맵 collection view 페이징 구현
  Spark-iOS/Podfile.lock
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkFlakeSparkFlake1.imageset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Storyboards/Dialogue/UpgradeFlakeDialogue.storyboard
  Spark-iOS/Spark-iOS/Source/Cells/HabitRoom/UpgradeFlakeCVC.swift
  Spark-iOS/Spark-iOS/Source/Classes/UpgradeFlakeCarouselLayout.swift
  Spark-iOS/Spark-iOS/Source/Extensions/UIView+.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Dialogue/UpgradeFlakeDialogueVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
Labels: Feat, 👼타락pOwEr천사현규

#658 [Feat] #655 - RequestContainer 구현 및 Extension
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Source/NetworkServices/Feed/FeedAPI.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Home/HomeAPI.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/MyRoom/MyRoomAPI.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Notice/NoticeAPI.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Plugin/MoyaLoggerPlugin.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Plugin/RequestContainer.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Notice/NoticeVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/StorageVC.swift
Labels: Feat, 🧚‍♀️Devil『쥬노』

#671 [Merge] Develop 브랜치 -> Release-1.0.4 Branch로 머지
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Source/NetworkServices/Feed/FeedAPI.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Home/HomeAPI.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/MyRoom/MyRoomAPI.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Notice/NoticeAPI.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Plugin/MoyaLoggerPlugin.swift
  Spark-iOS/Spark-iOS/Source/NetworkServices/Plugin/RequestContainer.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Notice/NoticeVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/StorageVC.swift
Labels: 🧚‍♀️Devil『쥬노』

#672 [Fix] #617 - 인증사진 더보기 뷰 이미지 사이즈 medium로 변경
  Spark-iOS/Spark-iOS/Source/Cells/StorageMore/MoreStorageCVC.swift
Labels: Fix, 🧚‍♀️Devil『쥬노』
