Repository TeamSparker/Spark-iOS, pull requests merged in 2022-09, with the labels that each got.

#639 [Chore] #638 - Xcode 14 업데이트 프로젝트 세팅 업데이트
  Spark-iOS/Podfile.lock
  Spark-iOS/Spark-iOS.xcodeproj/xcshareddata/xcschemes/Spark-iOS.xcscheme
Labels: Chore, 👼타락pOwEr천사현규

#641 [Feat] #640 - 푸시알림별 화면 전환
  Spark-iOS/Spark-iOS/Resource/Constants/Notification.swift
  Spark-iOS/Spark-iOS/Source/AppDelegate.swift
  Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/CodeJoin/CodeJoinVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/MainTBC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: 🦹t없e맑은水빈, 🖐help_wanted🖐

#646 [Chore] #643 - 버전 및 빌드 업데이트(1.0.3)
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
Labels: Chore, 👼타락pOwEr천사현규, 🐓 Release

#647 [Chore] #645 - 앱 아이콘 단순화
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/100.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/1024 1.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/114.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/120.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/172.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/180.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/196.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/216.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/29.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/40.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/48.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/55.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/57.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/58.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/60.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/80.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/87.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/88.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: Chore, 👼타락pOwEr천사현규

#650 [Chore] #648 - merge `release-1.0.3` to `main` branch
  Spark-iOS/Podfile.lock
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS.xcodeproj/xcshareddata/xcschemes/Spark-iOS.xcscheme
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/100.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/1024 1.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/114.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/120.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/172.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/180.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/196.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/216.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/29.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/40.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/48.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/55.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/57.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/58.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/60.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/80.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/87.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/88.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Spark-iOS/Spark-iOS/Resource/Constants/Notification.swift
  Spark-iOS/Spark-iOS/Source/AppDelegate.swift
  Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/CodeJoin/CodeJoinVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/MainTBC.swift
  Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Labels: Chore, 👼타락pOwEr천사현규, 🐓 Release

#649 [Chore] #648 - merge `release-1.0.3` to `develop` branch
  Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/100.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/1024 1.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/114.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/120.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/172.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/180.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/196.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/216.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/29.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/40.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/48.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/55.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/57.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/58.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/60.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/80.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/87.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/88.png
  Spark-iOS/Spark-iOS/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: Chore, 👼타락pOwEr천사현규
